### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#1]
I still see the map at the bottom of the screen when on home in any screen resolution:

![screen shot 2015-01-23 at 17 00 36](https://cloud.githubusercontent.com/assets/7487883/5877710/cef53844-a321-11e4-9dcc-5792abbd8f9b.png)
![screen shot 2015-01-23 at 17 02 26](https://cloud.githubusercontent.com/assets/7487883/5877709/cef374fa-a321-11e4-8fec-021e2fb9b370.png)
![screen shot 2015-01-23 at 17 02 43](https://cloud.githubusercontent.com/assets/7487883/5877711/cef6dc76-a321-11e4-8fec-5340405a3bc7.png)
![screen shot 2015-01-23 at 17 02 55](https://cloud.githubusercontent.com/assets/7487883/5877713/cefb6d68-a321-11e4-8067-bcab70daea7e.png)
![screen shot 2015-01-23 at 17 03 05](https://cloud.githubusercontent.com/assets/7487883/5877712/cef73be4-a321-11e4-95a6-c485d1cc4157.png)

**Comment by bokiftw** [comment]
Sorry for the confusion but now this is fixed. Behaviour on the every browser heigh now is the same, and map is not showing at first.

**Comment by diplomod** [comment]
looks good!
