### ISSUE TITLE
Button seems blurry

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#10]
This does not look right:

![screen shot 2015-01-26 at 15 55 43](https://cloud.githubusercontent.com/assets/7487883/5901592/f40cd020-a573-11e4-879c-62914480390e.png)
![screen shot 2015-01-26 at 15 55 57](https://cloud.githubusercontent.com/assets/7487883/5901591/f400a908-a573-11e4-97b1-9e6183460696.png)

**Comment by bokiftw** [comment]
This is fixed now.

**Comment by diplomod** [comment]
Looks good. out of curiosity: How come?
