### ISSUE TITLE
Move Geological explanation, Links and Tags up below PICTURES

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#100]
Move this block below PICTURES:

![screen shot 2015-03-30 at 09 47 04](https://cloud.githubusercontent.com/assets/7487883/6893390/ca685002-d6cc-11e4-83af-a3d35b1d36a4.png)

**Comment by bokiftw** [comment]
Done. Now it is like this: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/submit/

**Comment by diplomod** [comment]
OK, thanks. But it was supposed to be below pictures. Can you move PICTURES up on top of GEOLOGISK FORKLARING?

**Comment by bokiftw** [comment]
Oh sorry, I just misread. I changed it!

**Comment by diplomod** [comment]
That's fine now.
But please have a look at #72
