### ISSUE TITLE
Responsiveness (please comment)

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#101]
See here my comments re mobile performance.
 @Immoz and @bokiftw  - please comment where it is your task (I don't know exactly)
- On iPhone, any layers (e.g. geofunn, nordryggstien) are shown. Also not default selected.
- On iPhone & iPad: Map does not react on multi-gesture, only entire page
- On iPad/portrait + landscape: map is not responsive (does not fill the screen)
  ![img_0132](https://cloud.githubusercontent.com/assets/7487883/6894491/ab34b93c-d6d6-11e4-8092-c0ba0ce6174d.png)
- On iPad/portrait: re arrow to map is missing:
  ![img_0130](https://cloud.githubusercontent.com/assets/7487883/6894492/ab498812-d6d6-11e4-96c0-d0c8a04b0b8d.png)
- on iPad/landscape: red arrow to map is shown but does not work:
  ![img_0129](https://cloud.githubusercontent.com/assets/7487883/6894497/b24268c8-d6d6-11e4-9234-b7821e218545.png)
- And as you can see, the pictures are devided in the middle of the screen

**Comment by bokiftw** [comment]
Okay, I will take a look on responsiveness and this red arrow.

**Comment by diplomod** [comment]
Thanks - 2 comments:
- iPad looks better.  I still don't see the red buttons for navigating up and down between the different parts of the page on Ipad though
- Smartphone (iPhone 5) is still pretty messy - can we improve the performance there?
  ![image1](https://cloud.githubusercontent.com/assets/7487883/6951303/ae1c0c82-d8ba-11e4-8d3c-bef355c4fdec.png)
  ![image2](https://cloud.githubusercontent.com/assets/7487883/6951307/ae213e8c-d8ba-11e4-99da-155e0dba81b2.png)
  ![image3](https://cloud.githubusercontent.com/assets/7487883/6951304/ae1ec85a-d8ba-11e4-9f33-78755e613e95.png)
  ![image4](https://cloud.githubusercontent.com/assets/7487883/6951308/ae21f80e-d8ba-11e4-9062-66d1343fefb9.png)
  ![image5](https://cloud.githubusercontent.com/assets/7487883/6951305/ae1ff93c-d8ba-11e4-8f34-effbc0d2ecb4.png)
  ![image6](https://cloud.githubusercontent.com/assets/7487883/6951306/ae20455e-d8ba-11e4-8628-8850677eede8.png)

**Comment by diplomod** [comment]
Any comments @bokiftw @Immoz ?

**Comment by bokiftw** [comment]
I fixed most of the things in the update for the sidebar to be shown by default. Since everything is okay on our server, I really don't know why this arrow behave like this on dokuhl server. So please can @Immoz take a look? Also I don't know how this 'vis nordryggen far so till nord ' is generated?

Anyways, iPhone 5 width is a bit short for all these content, in slider, what do you think about hiding the 'utforkse nordryggen' button on small devices? Other thing I can do is to make it smaller..

**Comment by bokiftw** [comment]
and yeah @Immoz , here are the new files for home and map styling. sidebar is now shown by default and red arrow improvements: https://www.dropbox.com/s/khhccjzien7sknv/update.zip?dl=0

**Comment by diplomod** [comment]
@Immoz Bitte checken - merci

**Comment by Immoz** [comment]
@lukassiedel will take care about this in the next few days

**Comment by diplomod** [comment]
echt jungs - dss haut so nicht hin:
![screen shot 2015-04-30 at 17 04 38](https://cloud.githubusercontent.com/assets/7487883/7415719/0cafc43a-ef5b-11e4-9a20-900dc1566b9d.png)
