### ISSUE TITLE
Kompletter Trail...

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#102]
Bzgl. Trail 3 Punkte:
1. Der aktuelle rote Trail soll mit dem blauen Trail verbunden werden ab diesem Punk bei Røros:
![screen shot 2015-04-01 at 11 04 56](https://cloud.githubusercontent.com/assets/7487883/6937839/fea81bb6-d85e-11e4-9a91-a5117d1acb1b.png)
Nur der Zipfel nach rechts unten ist die Alternative und kann blau sein.
2. "Rute 2" solte "Alternativ rute" heissen
3. Der Trail ist lückenhaft. Ich habe nochmal ein update bekommen - aber komplett sind wir immer noch nicht.
Kann man die End-und Anfangspunkte der fehlenden Stücke einfach zusammenhängen mit einer geraden verbindung?
Wenn ja, dann würde ich nochmal die neuen Teilstücke herunterladen lassen und die als .gpx zukommen lassen.

**Comment by Immoz** [comment]
Ja die können wir einfach mit einer gerade linie verbinden.

**Comment by diplomod** [comment]
OK - ich organisiere die neuen gpx files

**Comment by diplomod** [comment]
Siehe bitte auch Punkte 1 & 2 - wie heute besprochen
