### ISSUE TITLE
Review-Prozess

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#103]
Wie schaut es eigentlich damit aus? Ist laut Google Spreadsheet erledigt.
Wie kann ich testen?

**Comment by Immoz** [comment]
Wenn ein geofunn submittet wird erscheint er im Adminbereich bei geofunns als "draft". Dort kannst du ihn anklicken/editieren und wenn alles passt "publishen".

**Comment by diplomod** [comment]
Wie ist das mit emails? Der Ersteller soll eine erhalten und die als Reviewer eingetragenen User mit Lik auf den draft.

**Comment by Immoz** [comment]
Die mail an den ersteller sollte raus gehen (hab ich aber noch nicht auf dokuhl getestet). Das mit der mail für die reviewer war mir so nicht bewusst - werd ich noch anpassen.

**Comment by diplomod** [comment]
Bitte Mails beim Einstellen eines neuen Geofunn an hans@geonova.no mit Link zum geofunn im Admin-Bereich. Geht das?

**Comment by diplomod** [comment]
Ich bekomme immer noch keine Mails. Aber das machen wir ja jetzt eh anders, daher der issue zu
#158
