### ISSUE TITLE
Test all issues

### ISSUE THREAD

**Issue by bokiftw** [diplomod/nordryggstien.no#104]
Hey Hans,

I have sent new files to @Immoz. After they merge things, please take a look again on all these issues are they fine. I am a bit messed if I changed everything, because I had to do it again on they side.

Just to know, now it is a bit hard to sync and merge all files after doing new enhancements on our side and then doing on their side. So please, take a look if everything is correct so we can merge this once, in order not to have overlapping.

You can write me here in comments if something is wrong.

**Comment by diplomod** [comment]
Thanks! I will check as soon as they're merged.
