### ISSUE TITLE
Default open search in map menu + menu default opened

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#105]
The search is hard to fin in the menu of the ma.

Can you edit this search field so that is default open like this?
![screen shot 2015-04-01 at 20 47 50](https://cloud.githubusercontent.com/assets/7487883/6948790/64491f46-d8b0-11e4-9c4d-c81564fa60eb.png)

And the menu shuld be default opened - we should not require the users to find it out themselves that there is a menu.

**Comment by bokiftw** [comment]
Okay, this is done. - http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/

**Comment by diplomod** [comment]
very good. please make sure it's transferred and updated on the other server

**Comment by diplomod** [comment]
Excellent, thanks!
