### ISSUE TITLE
Geofunn & Hytter in der Nähe

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#106]
Kriegen wir die noch ausgefiltert und angezeigt?

![screen shot 2015-04-01 at 22 08 14](https://cloud.githubusercontent.com/assets/7487883/6951444/abf35644-d8bb-11e4-8d68-47fd3ad2c472.png)

**Comment by Immoz** [comment]
Jo das ist auf jeden fall machbar.

**Comment by lukassiedel** [comment]
in arbeit

**Comment by lukassiedel** [comment]
ist gemacht, allerdings sollten wir noch klären welches bild bei den hytter reinsoll (oder ob dieses bleiben soll) weil wir keine in der db gespeichert haben. Außerdem ob wir ein Default bild für die geofunn nehmen wenn kein bild vorhanden ist.
immoment werden jetzt jeweils die 5 nächsten angezeigt.
allerdings sind mehrere geofunns scheinbar 3fach in der datenbank angelegt. wobei mir nicht ganz klar ist warum

**Comment by diplomod** [comment]
Ja top.

ich hab nur immer in der MItte 3 Stück angezeigt. Bug?
![screen shot 2015-04-25 at 21 59 41](https://cloud.githubusercontent.com/assets/7487883/7334535/98847852-eb96-11e4-8d02-385f563cba3c.png)

Default Bild geofunn derweil mal das:
![1440x365 geofunn_neutral](https://cloud.githubusercontent.com/assets/7487883/7334536/ae20fa0a-eb96-11e4-86f1-c2723c3fc0a5.png)

Default Hytter: Nimm einfach das: http://cdn.turistforeningen.no/images/we/iy/9l-940.jpg

**Comment by lukassiedel** [comment]
geht klar. ja der tom hat mir grad mitgeteilt, das die geofunns vom sprachplugin teilweise mehrfach angelegt werden für die verschiedenen sprachen. das muss ich noch abfangen. bilder werden eingebaut. das für die geofunn wirds nur bissl zusammenschieben weil das so breit ist

**Comment by lukassiedel** [comment]
sollen bei den nächsten geofunn eigentlich auch die other_geofunn mit rein?

**Comment by lukassiedel** [comment]
"ich hab nur immer in der MItte 3 Stück angezeigt. Bug?" fixed

**Comment by diplomod** [comment]
Nope, nur dir nordryggstien-relevanten

**Comment by lukassiedel** [comment]
gut hab ich auch so gemacht

**Comment by diplomod** [comment]
alles klar. Das mit den Bildern der Hytter müssen wir dann mal gesondert in Angriff nehmen. Merci.
