### ISSUE TITLE
Not all fjellheimer are shown

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#108]
We have now created 35 fjellheimer, but only 10 of them are shown in the overview page:
http://dokuhl.de/nordryggen/about/mountains/

**Comment by diplomod** [comment]
We have deploaed the udate, but this is still incorrect.

**Comment by bokiftw** [comment]
I think I solved this with improvements in these files: https://www.dropbox.com/s/m18bjz89pvbwmy7/post%20types.zip?dl=0

Please @Immoz replace these 3 files in nordryggen folder.

**Comment by diplomod** [comment]
Now it looks good!
