### ISSUE TITLE
Kann man am Beginn des blauen Trail ein "E1" anzeigen? 

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#109]
Vielleicht als Button oder so ähnlich:

![screen shot 2015-04-08 at 15 10 34](https://cloud.githubusercontent.com/assets/7487883/7045787/6e9431a6-de01-11e4-8a1e-958051df41d6.png)

**Comment by philipdomann** [comment]
Steht für? Link dahinter?

**Comment by diplomod** [comment]
Kein Link, nur eine Art Label (E1 ist sehr bekant)

**Comment by philipdomann** [comment]
Okay hab mich informiert, der Stein ist ja voll cool http://de.wikipedia.org/wiki/Europ%C3%A4ischer_Fernwanderweg_E1 :-)

**Comment by diplomod** [comment]
:)

"Stien" = Weg

**Comment by lukassiedel** [comment]
wenn ichs in der Aufwandsschätzung gelesen hab soll hier nur noch im Menü Rute 2 in E1 umbenannt werden?

**Comment by diplomod** [comment]
korrekt

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
top
