### ISSUE TITLE
Normal Wordpress comments, not Disqus

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#11]
I agreed with Michael that we use wordpress comments, not Disqus:

![screen shot 2015-01-26 at 16 04 26](https://cloud.githubusercontent.com/assets/7487883/5901739/22293d94-a575-11e4-9e72-44bc1274f7b8.png)

**Comment by bokiftw** [comment]
We disabled Disqus and switched to Wordpress comments system. It was styled like on the desired design as much as it can be, since it forces some other html architecture and links to be shown.

**Comment by diplomod** [comment]
All right :)
