### ISSUE TITLE
Default Ansicht/Zoom-Level Map: Jotunheimen & Hardangervidda

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#110]
So ungefähr sollte die Map angezeigt werden beim erstmaligen Öffnen/Ansteuern:

![screen shot 2015-04-09 at 16 07 24](https://cloud.githubusercontent.com/assets/7487883/7076602/ecb54b92-df0a-11e4-82f8-8c61eca48861.png)

**Comment by philipdomann** [comment]
Wenn man den Button "mouse zoom wheel on" klickt?

**Comment by diplomod** [comment]
nein, geich wenn man vom Hauptmenü runter kommt oder den roten Button unten auf dem Startscreen clickt.

**Comment by philipdomann** [comment]
Der Pfeil soll also die Karte wie gezeigt positionieren.
Die Karte kann dann auch gleich gezoomt und verschoben werden?
Oder gibt es weiter den Button "mouse zoom wheel on" zum De(aktivieren) von Zoomen und Verschieben?

**Comment by diplomod** [comment]
- Aktiv verschieben via Click+Mouse-Bewegung: Ja
- Zoomen via +/-: Ja
- Öffnen von geofunn: Ja

Auto-zoom via Mouse-wheel-scrolling: Nein - erst nach Aktivierung durch den neuen Spezial-Button
(Sonst bleibt man beim runterscrollen immer in Map hängen und zoomt sofort zum Mond)

V.a. das Öffnen von geofunn ist wichtig - das macht mich gerade wahnsinnig, dass ich erst den Button aktivieren muss! Der soll sich ausschließlich, exklusiv und nur auf das automatische Zoomen via Mouse-Wheel beschränken, alles andere soll davon unabhängig ganz normal funktionieren.

**Comment by lukassiedel** [comment]
"V.a. das Öffnen von geofunn ist wichtig - das macht mich gerade wahnsinnig, dass ich erst den Button aktivieren muss! "
Das geht ja inzwischen wieder. den Zoom kann ich eins runternehmen, so dass es besser an den gezeigten zoom herankommt. 
Soll wie auf dem Bild auch das Menü eingeklappt sein am Anfang?

**Comment by diplomod** [comment]
Super. Menü default immer ausgeklappt - also passt so wie es ist.
