### ISSUE TITLE
Change all "rocksite" to "geosite"

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#112]
Please change all "rocksite" to "geosite":

![screen shot 2015-04-08 at 16 11 58](https://cloud.githubusercontent.com/assets/7487883/7047013/13812ea0-de0a-11e4-885b-5516f223ffb9.png)

I was able to trabslate in the forms, but can't do it in the code.

**Comment by diplomod** [comment]
In the submit site, this is now correct for the button at the bottom:
![screen shot 2015-04-10 at 14 46 38](https://cloud.githubusercontent.com/assets/7487883/7087950/764f6916-df90-11e4-96ae-65b483dc12c2.png)
and the message after:
![screen shot 2015-04-10 at 14 47 59](https://cloud.githubusercontent.com/assets/7487883/7087965/9dca2454-df90-11e4-88d3-cf2d7b4f4448.png)

But the headline is still incorrect:
![screen shot 2015-04-10 at 14 46 24](https://cloud.githubusercontent.com/assets/7487883/7087952/7fb5dc38-df90-11e4-94dd-565b94c633b6.png)

**Comment by bokiftw** [comment]
Huh, I just saw this. haven't noticed this before. Okay I have changed this and will send updated files to Lukas.

**Comment by diplomod** [comment]
you're a rockstar! :) Thanks!

**Comment by diplomod** [comment]
looks good!
