### ISSUE TITLE
Button in about of Norwegian version: "Mountain regions" => "Fjellheimer"

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#113]
![screen shot 2015-04-08 at 16 22 40](https://cloud.githubusercontent.com/assets/7487883/7047228/9217d07e-de0b-11e4-85d3-71202a8dbc46.png)

**Comment by bokiftw** [comment]
This is also up to incorrect placement of the languages files. As I mentioned in comment before, @Immoz  please update language files in desired folders. Thanks!

**Comment by diplomod** [comment]
still open

**Comment by diplomod** [comment]
fixed now, thanks
