### ISSUE TITLE
Geological Attractions don't work

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#114]
We have set up some attractions and I created a page based on the "attractions" template and added it to the menu. However, I can't make it visible - it does not find the page:

![screen shot 2015-04-02 at 16 41 04](https://cloud.githubusercontent.com/assets/7487883/6966219/9f4a9e88-d957-11e4-8b36-131df47c0a8c.png)
![screen shot 2015-04-02 at 16 41 10](https://cloud.githubusercontent.com/assets/7487883/6966218/9f4ac87c-d957-11e4-803a-8b6fb60abbb3.png)
![screen shot 2015-04-02 at 16 41 47](https://cloud.githubusercontent.com/assets/7487883/6966220/9f4cc4d8-d957-11e4-8427-09ebff4dfe73.png)
What's the problem?

**Comment by diplomod** [comment]
moved from comment in #98

**Comment by bokiftw** [comment]
Hmm I don't see the bug here, since I managed to make the page. I just added it from the list on the left, and took care of languages. At the moment it works, as far as I can see.

Please take a look again if it is fine again.

**Comment by bokiftw** [comment]
I forgot to add, I removed the parent just in case. I doesn't need to have parent page, and I guess its better for these pages not to have.

**Comment by diplomod** [comment]
OK - looks good now, thanks
