### ISSUE TITLE
Button incorrect

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#115]
This should say

"UTFORSKE NORDRYGGSTIEN"

![screen shot 2015-04-08 at 16 51 53](https://cloud.githubusercontent.com/assets/7487883/7047859/a27d7f1e-de0f-11e4-9568-e5c2a05e6b0b.png)

**Comment by bokiftw** [comment]
@Immoz please update the language files which I sent you in the .zip (visit link: http://cl.ly/3n250y2X3427)

Also make sure it is replaced into wp-content/languages and nordryggen folder (in nordryggen JUST .mo files as you can see how it is now).

**Comment by bokiftw** [comment]
NEW LANGUAGE FILES HERE - UPDATED: https://www.dropbox.com/s/og6kh1rh8ne9zip/languages.zip?dl=0

**Comment by diplomod** [comment]
@Immoz gesehen?

**Comment by diplomod** [comment]
Fixed it now. Thanks
