### ISSUE TITLE
Responsiveness Map optimieren

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#116]
Wie besprochen: Map solte mit Browserröße "mitgehen"

**Comment by philipdomann** [comment]
Gerade angetestet, geht gut daher meine Frage "Wann geht die Karte den nicht mit bzw. wo verhält die Karte sich nicht wie von dir erwartet?"

**Comment by diplomod** [comment]
Das Problem ist, dass die Karte bei kleineren Bildschrimgrößen ab einer bestimmten Größe (z.B. Bereits auf meinem 15'' MacBook) nicht vom unteren Bildschirmrand begrenzt wird, sondern man immer noch weiter runter scrollen kann/muss, um die ganze Karte zu sehen.
D.h. unten bleibt immer noch ein Teil der Karte außerhalb meines Bildschirms.
Konsequenterweise sollte aber wirklich am unteren Bildschrimrand der nächste Screen-Teil beginnen (in dem Fall Community) und nichts mehr von der Map angezeigt werden.

**Comment by diplomod** [comment]
Geht jetzt...
