### ISSUE TITLE
"Les mer" in der Preview auf der Map geht im Firefox geht nicht

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#117]
Öffnet im Firfox nicht, nur Safari und Chrome:

![screen shot 2015-04-09 at 16 12 43](https://cloud.githubusercontent.com/assets/7487883/7068571/92a31080-ded3-11e4-977a-1325e4bd2c62.png)

**Comment by philipdomann** [comment]
Welche Version? Bei mir gehts mitn Firefox

**Comment by philipdomann** [comment]
@diplomod Bitte überprüfen, sollte gefixt sein

**Comment by diplomod** [comment]
Ja, geht.
