### ISSUE TITLE
Kann man das Grau in der Karte mit einem Bild ersetzen?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#118]
![screen shot 2015-04-09 at 16 27 04](https://cloud.githubusercontent.com/assets/7487883/7068820/57eaf2ee-ded5-11e4-8392-3089e60940a5.png)

**Comment by Immoz** [comment]
ja das sollte gehen

**Comment by lukassiedel** [comment]
wenn du mir sagst welches bild wird das erledigt :)
wenn es ein bild ist, was nur einmal angezeigt werden soll, sollte die auflösung min irgendwas um die 2200x900 haben. wenn wir es aber in höhe und breite wiederholen können (ohne das es komisch aussieht) kann es auch eine kleinere sein

**Comment by diplomod** [comment]
OK -keine wiederholung des Bildes, das sieht meistens blöd aus. Wie wäre es mit dem?
![desember 1 - nordryggen](https://cloud.githubusercontent.com/assets/7487883/7332903/de86dc66-eb58-11e4-9b75-92d39f32c68f.JPG)
(sollte so um die 4000 px breit sein - lass mich wissen, wenn github das runter rechnet, dann schicke ich das Original via Email)

**Comment by lukassiedel** [comment]
das reicht von der größe her auf jeden fall denk ich. ist eher sogar so das es zu groß ist^^ man sieht fast nur himmel ^^ habs mal hochgeladen

**Comment by diplomod** [comment]
Cool jedenfalls. Aber zu viel Himmer, korrekt. Kannst du es entprechend abschneiden?

**Comment by lukassiedel** [comment]
habs kleiner gemacht ich denke jetzt siehts ganz gut aus

**Comment by diplomod** [comment]
Läuft
