### ISSUE TITLE
Typo in button on map

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#119]
It should say "DITT" (double T)

Who can help me here?
![screen shot 2015-04-09 at 16 28 32](https://cloud.githubusercontent.com/assets/7487883/7068845/92dbac90-ded5-11e4-97f6-eadd870bfee0.png)

**Comment by bokiftw** [comment]
I updated this with a new language files i have sent in pervious comments

**Comment by diplomod** [comment]
still wrong

**Comment by diplomod** [comment]
Now we got it :) Thanks.
