### ISSUE TITLE
Typo in submit

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#121]
It must say "INN" (double N in INN)

![screen shot 2015-04-09 at 16 33 23](https://cloud.githubusercontent.com/assets/7487883/7069049/062e3838-ded7-11e4-8002-a342cfd58b94.png)

**Comment by bokiftw** [comment]
Hmm I see double NN?
![screen shot 2015-04-09 at 17 36 43](https://cloud.githubusercontent.com/assets/5833593/7070444/4579afb0-dedf-11e4-8614-04642297064b.png)

**Comment by diplomod** [comment]
That's on the submit page. The NN is missing on the login page :)

**Comment by bokiftw** [comment]
Okay, if it's login then I made this page all in english, since we didnt put translations yet. So this will also be fixed after backend guys correctly merge new language files.

So, it will be LOG IN, all in english.

**Comment by diplomod** [comment]
Typo is still there

**Comment by bokiftw** [comment]
Wait, did the backend guys read my comments and updated files? I don't have an access to the server so I can't update files by myself..

**Comment by diplomod** [comment]
working on it - hopefully we get it fixed

**Comment by diplomod** [comment]
Still there: http://dokuhl.de/nordryggen/login/

![screen shot 2015-04-10 at 14 34 15](https://cloud.githubusercontent.com/assets/7487883/7087735/b0ff9880-df8e-11e4-988a-995a2803fd6f.png)

**Comment by bokiftw** [comment]
Okay, @Immoz can you check the page-login.php code? It should be like this, with the accent on the lines 14 and 17. They must be like this in the picture:
![screen shot 2015-04-10 at 16 13 02](https://cloud.githubusercontent.com/assets/5833593/7089512/a68cbb86-df9c-11e4-9b4f-d89459ff676d.png)

**Comment by Immoz** [comment]
@lukassiedel will take care about this in the next few days

**Comment by diplomod** [comment]
finally :)
