### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#122]
it should say

"NORDRYGGENS FJELLHEIMER"

![screen shot 2015-04-09 at 16 40 36](https://cloud.githubusercontent.com/assets/7487883/7069127/4d3ce7e2-ded7-11e4-8d58-f3c47b466652.png)

http://dokuhl.de/nordryggen/about/mountains/

**Comment by bokiftw** [comment]
This actually is not a bug, this is how the page is named inside wordpress. So this is a title of the page, which you can change. Now I changed to 'Nordryggens'.

it can be changed here:
![screen shot 2015-04-09 at 17 23 35](https://cloud.githubusercontent.com/assets/5833593/7070140/5b73af52-dedd-11e4-8e20-78b14a73709e.png)

**Comment by diplomod** [comment]
OK, thansk!
