### ISSUE TITLE
Firefox mag den Link zur Map aus Unterseiten heraus nicht

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#123]
Wenn man im Firefox beispielsweise aus http://dokuhl.de/nordryggen/about/geologi/ auf den Link im Menü "NORDRYGGSTIEN PÅ KATRTET" (http://dokuhl.de/nordryggen/#map) klickt, endet man im Footer. 

Im Safari und Chrome gehts.

**Comment by philipdomann** [comment]
Stimmt hier verhält sich Firefox anders

**Comment by diplomod** [comment]
nach wie vor...

**Comment by lukassiedel** [comment]
ich hab jetzt eine ganze Weile nach einem Fehler gesucht und es scheint daran zu liegen das firefox damit nicht klarkommt, dass die id map (die als anchor benutzt wird) mehrmals (auch bei den markern) auftaucht. daher musst ich ein unsichtbares div einfügen mit der id "map-anchor" (vorläufig, können wir auch umbenennen) Daher bitte den link von "NORDRYGGSTIEN PÅ KATRTET" zu  http://dokuhl.de/nordryggen/#map-anchor umbenennen bzw. kannst du dir auch einen anderen Namen aussuchen für den anchor den ich dann einfüge, nur "map" ist wie gesagt schon vergeben und es würde etwas zu viel aufwand bedeuten alles wo die id "map" verwendet wird umzubenennen

**Comment by diplomod** [comment]
OK - bitte #kart machen, danke

**Comment by lukassiedel** [comment]
gut ist auf dokuhl

**Comment by diplomod** [comment]
So, jetzt geht's auf Safari nicht mehr. Safri öffnet die Karte nicht bei Click auf den Menü-Item
Wederbei /#map noch bei /#kart

**Comment by lukassiedel** [comment]
wie schon im skype geschrieben^^ geht wieder :)

**Comment by diplomod** [comment]
super, danke
