### ISSUE TITLE
Can we add a picture here on top?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#124]
Instead of the text "Under construction" a picture like this:

![page_is_under_construction](https://cloud.githubusercontent.com/assets/7487883/7069518/890ffb68-ded9-11e4-8bc5-753e7e5ac87a.jpg)

**Comment by bokiftw** [comment]
Yes, we can. I will change the intro field into the image filed, and you will be able to upload an image. After, it can be changed to text field. Shall I do it like this?

**Comment by diplomod** [comment]
Is it possible to have both? Or an option to choose?

**Comment by bokiftw** [comment]
Well, in that case I can put a WYSIWYG editor, therefore you will have more options to put there. Is that ok?

**Comment by diplomod** [comment]
perfect!

**Comment by bokiftw** [comment]
It's done, you will see in the update.

**Comment by diplomod** [comment]
OK, great.

**Comment by diplomod** [comment]
works great, thanks
