### ISSUE TITLE
Search does not always work in Safari

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#126]
I cannot use the search function in the menu bar on all pages when I'm using Safari - e.g. when I use it once and then I get to the page with the search results, I cannnot open the search again and search for something different. CLicking on the search symbol does not open the search bar...

![screen shot 2015-04-10 at 12 03 44](https://cloud.githubusercontent.com/assets/7487883/7085725/e8f9777a-df79-11e4-86a4-4b04f1871acf.png)

So far, I found that it does not work on 
- Search results pahe
- Login page

**Comment by bokiftw** [comment]
This titles in menu are definitely too long for the menu like this. It not designed for such a long menu items, therefore it doesn't have space to spread. So I honestly suggest you to put shorter titles.. that cause on of the bugs English and German languages.

Other than that I can't find that bug really. It works fine for me even on search page and login. Just tested it.

**Comment by bokiftw** [comment]
Even I couldn't manage to make this bug appear, I tried to improve code a bit, and here is an update: https://www.dropbox.com/s/aecc0rg8ronpt2k/search.zip?dl=0

@Immoz Please, update these files. Update content-search.php in order to get search images and styling like I did on Hans demand. And update style.css and paste _menus.scss inside navigation folder inside scss. This will improve some things and update general search page. Thanks!

**Comment by bokiftw** [comment]
What's going on with these issues, are they fixed, since I would like to finish all bugs first and start with enhancements?

**Comment by diplomod** [comment]
Works on search results page, not on login page.

I understand that this is caused by the lenght of the titles in the menu, correct? Unfortunately, we cannot shorten the title.
Can you make the font a little bit smaller eventually so that the search has enough space?

**Comment by bokiftw** [comment]
Okay I changed the width a bit, so now it is okay. But I really can't see the problem since it is working for me. Can you explain me? 

Here is that I see it works:
http://cl.ly/image/1542042m053v

Sorry, I recorder the home screen, but it also work on login page.

**Comment by diplomod** [comment]
Thanks. It always worked on home. Now also on login page and search results page. Perfect.
