### ISSUE TITLE
Doch Checkboxes an Stelle von Radios bei Geological Categories

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#128]
Frag nicht... :)

![screen shot 2015-04-10 at 12 12 48](https://cloud.githubusercontent.com/assets/7487883/7085853/3bc71614-df7b-11e4-9c52-433aec08cb65.png)

ich hab mir die Form angeschaut - ich trau mcih das nicht selber machen.

**Comment by Immoz** [comment]
jo da muss auch was im backend angepasst werden. kümmer mich sobald wie möglich drum.

**Comment by lukassiedel** [comment]
sollen dann auch mehrere Kategorien auswählbar sein oder trotzdem nur eine?

**Comment by diplomod** [comment]
genau - deshalb ja checkboxes (für mich ist der unterschied zw. checkbox und radio, dass man bei ersterem mehrfach auswählen kann. Bei radios nicht)

**Comment by lukassiedel** [comment]
ja is richtig. hätte ja aber auch sein können das es rein um das design geht^^

**Comment by diplomod** [comment]
Passt, super. merci
