### ISSUE TITLE
Typo in Norwegian Community section

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#129]
The link at the bottom is missing an "s": http://dokuhl.de/nordryggen/

![screen shot 2015-04-10 at 14 54 04](https://cloud.githubusercontent.com/assets/7487883/7088102/aa5ab9a8-df91-11e4-863e-b574c2145866.png)

**Comment by bokiftw** [comment]
this is same as bug above. I have no idea what happened and after what. Gonna see this

**Comment by diplomod** [comment]
fixed, thanks
