### ISSUE TITLE
Pictures same hight

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#13]
Do we have to upload the correct picture size or is the different hight of the pictures caused by another error?
If the picture size must be a specific format, please indicate exactly what that is.
![screen shot 2015-02-03 at 15 48 59](https://cloud.githubusercontent.com/assets/7487883/6022348/665a9826-abbc-11e4-9c14-95703b57bcee.png)

**Comment by bokiftw** [comment]
This was actually bug on Chrome browser as far as I am concerned, that's why I didn't notice that. Now it is fixed.
