### ISSUE TITLE
English version: "NORDRYGGEN NEWS" => "NEWS"

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#130]
http://dokuhl.de/nordryggen/en/

![screen shot 2015-04-10 at 14 56 34](https://cloud.githubusercontent.com/assets/7487883/7088169/20e3b37c-df92-11e4-8574-e3f454cde841.png)

**Comment by bokiftw** [comment]
@Immoz  Please, update new language files for English language in the nordryggen root folder and wp-content/languages. So copy ONLY .mo file inside nordryggen and both files inside wp-content/languages. Thanks! 

Files: https://www.dropbox.com/s/edr5vcv97tgpbki/enUS.zip?dl=0

**Comment by Immoz** [comment]
Ok, language files should now be updated.

**Comment by diplomod** [comment]
Excellent, thanks!
