### ISSUE TITLE
Links in about miss first letter

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#131]
This is very wrong - either it's a problem in the language file or in the page structure?
http://dokuhl.de/nordryggen/about/

![screen shot 2015-04-10 at 15 08 07](https://cloud.githubusercontent.com/assets/7487883/7088389/7fdc74ee-df93-11e4-944e-45fc7b8bfd33.png)

G in GEOLOGI missing
F in FJELLHEIMER missing
K in KART missing
N in NYHETER
L in LES MER... missing

Only Community is correct

Same problem with the right of the two buttons at the bottom of the page:

![screen shot 2015-04-10 at 15 10 03](https://cloud.githubusercontent.com/assets/7487883/7088420/bb28e88e-df93-11e4-9099-be1de6a4b0c3.png)

**Comment by bokiftw** [comment]
Wow, I have no idea what happened here! I am really confused. After doing what this happened?

In my language files (.po/.mo) everything is like it should be! See image:
![screen shot 2015-04-10 at 16 42 35](https://cloud.githubusercontent.com/assets/5833593/7090110/ee82bedc-dfa0-11e4-815d-3d5c77e6da97.png)

So this must be working. Can you @Immoz screenshot me the current version of the language NO file on server? You can open it with Poedit free.

**Comment by bokiftw** [comment]
I just tested this on our server. So updated files I sent you really works and it's alright

**Comment by Immoz** [comment]
Sorry there was a damaged language file on the server - should now be fixed.

**Comment by bokiftw** [comment]
Great!

**Comment by diplomod** [comment]
Yes, looks fine now - thanks
