### ISSUE TITLE
Change wording in button

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#132]
Please replace "NORDRYGGEN" with "NORDRYGGSTIEN" in these wto buttons:
About http://dokuhl.de/nordryggen/about/
![screen shot 2015-04-10 at 15 11 01](https://cloud.githubusercontent.com/assets/7487883/7088439/e28d6594-df93-11e4-9db6-594685a3d366.png)

Kart: http://dokuhl.de/nordryggen/#map 
![screen shot 2015-04-10 at 15 12 02](https://cloud.githubusercontent.com/assets/7487883/7088447/f55f5b46-df93-11e4-9ef1-c09b8d40090e.png)

**Comment by bokiftw** [comment]
This is also done.

**Comment by diplomod** [comment]
Perfect, thanks.
