### ISSUE TITLE
Ad space

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#134]
We need to add ad space.

My suggestions:
1) Home (this one could eventually "fly in" and have a x-button to make it disappear)
![folie1](https://cloud.githubusercontent.com/assets/7487883/7102092/03075716-e076-11e4-9255-e7f91cb1fc7a.png)

2) Within each geofunn, e.g. left of the text, skyscraper format:
![folie2](https://cloud.githubusercontent.com/assets/7487883/7102094/07cd76c2-e076-11e4-8ceb-19a9d2fd2317.png)

3) Map menu:
![folie3](https://cloud.githubusercontent.com/assets/7487883/7102096/0be1b05c-e076-11e4-8f06-bc3ce827ab81.png)

4) Info pages (Geologi, Fjellheimer etc.)
![folie4](https://cloud.githubusercontent.com/assets/7487883/7102097/105f6f66-e076-11e4-9f54-e16b990bff93.png)

**Comment by bokiftw** [comment]
Which Ads do you think of? Are you just going to use images or some aAds like Google or AdRotate?

Also I don't suggest you to put Ad on the top of the home, over the slider, it will be to much for rendering the page and also not good for mobile devices. It will take to much of resources. Also, this position under the map sidebar, is not good, what would you do it this list become bigger and use more space?

**Comment by diplomod** [comment]
Good questions.
Google ads could also make sense. Is it possible?

Regarindg home: Understood, thank you for your advise.
Is it easier if we put one on top, like this:
![screen shot 2015-04-17 at 10 58 57](https://cloud.githubusercontent.com/assets/7487883/7198963/f0a7db2a-e4f0-11e4-9bba-0234ca7c46db.png)

Regarding Map sidebar: No problem, the list will not be extended. And if, we just make the ad smaller.

**Comment by bokiftw** [comment]
We can implement Google Ads, I will search the best way to do. But first of all, think of it how you will use your ads? Because, Google will have control of the ads and will put ads on their own. You will not have that much control. Other option is that you choose which ad will put, and in that case that would be simple image banner. So think of what suits you the mosts. If you have additional questions feel free to ask!

Anyways, for the home we can put it on top, static.

**Comment by diplomod** [comment]
Re Google Ads: I know. We will begin with simple image banners. But I would like to have the option - if it is possible to prepare for both.
If not, image banner only will do.

Re top banner: Great - not too high though, I don't want to take too much space from the picture. Eventually Igor can advise here.

**Comment by bokiftw** [comment]
Unfortunately, I can't make them dynamic so we have both in same time, because it is made in totally different ways. Then I will make them like image banners.

I have discussed with Igor, and we defined the dimensions. Also we agreed that for geology, fjellheimer is better to be similar to home page. Just on the top like in the home page. It will look like something this. 
![nordyggen_geologi_1024](https://cloud.githubusercontent.com/assets/5833593/7230804/63f311da-e771-11e4-8343-11fc5ba85596.png)

**Comment by diplomod** [comment]
OK, thanks. Good idea.
Please let em know the dimensions.

**Comment by bokiftw** [comment]
I have done this. You can see here: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/
and also here: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/490-2/

Go to Appearance > Widgets and there you will see the space for widgets. See below:
![screen shot 2015-04-22 at 17 13 06](https://cloud.githubusercontent.com/assets/5833593/7277992/2fdd6140-e913-11e4-8591-117874f34125.png)

**Comment by diplomod** [comment]
OK, thanks.

Actually, the banner on home is not very good. I thought this is for fjellheimer page etc. only. But this way, it moves the picture too far down and it wastes space on the left and on the right.
It should be less high and over the entire screen, like in my suggestion above.
ALso above the menu.
See for example the banner on http://www.geo365.no/

Can you change that?

**Comment by diplomod** [comment]
OK, this is great.

Please make sure that it is transferred to the other system.

**Comment by bokiftw** [comment]
Wait, I am confused a bit. Do I need to change anything from now? Because I haven't changed anything. Do you agree on this? Also I discussed this with Igor, he suggested dimensions and positions to be like this.

**Comment by diplomod** [comment]
Sorry - my last comment was obviously for another issue - I have deleted it.

Please refer to my questions in what is my last comment now. Thanks!

**Comment by bokiftw** [comment]
OK, I made new one only for the Homepage, and it is full width like you said.

**Comment by diplomod** [comment]
Great.
Question: When there is no ad, the page just looks as it does not, correct?

**Comment by bokiftw** [comment]
Yes, exactly. When there is no ads, it will look like before. No white space.

**Comment by diplomod** [comment]
OK, I found it.

How can I now place a banner and link it?

**Comment by bokiftw** [comment]
I updated this on the dokuhl server. Please take a look, I prepared everything for you to just upload image and paste. Appearance > Widgets go to banners and click on Image box. You will see the space for uploading image.

**Comment by diplomod** [comment]
OK, now I got it. Works perfect, thanks a lot.

optimization:
When I add a banner on home, the main picture moves down of course. This is ok, but the problem is that the red arrow that directs down diappears, too.

Can you adjust the responsiveness accordingly that the screen bottom adjusts when a banner is placed?

Arrow not visible:
![screen shot 2015-05-07 at 14 51 14](https://cloud.githubusercontent.com/assets/7487883/7515614/ba9b4d7c-f4c8-11e4-96bc-022d3f2c01e0.png)

![screen shot 2015-05-07 at 14 50 48](https://cloud.githubusercontent.com/assets/7487883/7515626/cf9dd366-f4c8-11e4-9e25-1ff30aed6c6a.png)

Ideal:
![screen shot 2015-05-07 at 14 51 05](https://cloud.githubusercontent.com/assets/7487883/7515624/c86d0684-f4c8-11e4-8413-b27cde5500b0.png)

**Comment by bokiftw** [comment]
This should be fine now.

**Comment by diplomod** [comment]
OK - please send @lukassiedel the update - thanks!

**Comment by bokiftw** [comment]
Done, works on the server.

**Comment by diplomod** [comment]
perfect, thanks!
