### ISSUE TITLE
Line break in bayerngas logo text

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#136]
Please change this to 

POWERED BY GEOFUNN
A PROJECT WITH

![screen shot 2015-04-12 at 19 54 37](https://cloud.githubusercontent.com/assets/7487883/7106779/25b2df32-e14e-11e4-97fb-11bbf8f93bf0.png)

**Comment by bokiftw** [comment]
The is done. I will send updated files when we finish all of these

**Comment by diplomod** [comment]
thanks, fine.
