### ISSUE TITLE
"mouse wheel zoom" button wirklich nur auf das Mouse Wheel Zoomen beschränken

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#138]
Aktuell geht bis auf das manuelle Zoomen über +/- gar nichts in der Map, bevor ich nicht den mouse wheel zoom button gelickt habe.
Tatsächlich sollen aber alle Links (geofunn, "Vis nordryggen fra sor til nord") sowie das manuelle verschieben der Map schon funktionieren, auch wenn das mouse wheel zoom-Dings noch inaktiv ist.

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
Sehr gut, merci
