### ISSUE TITLE
Suchergebnis in der Map mit falschem Symbol angezeigt

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#139]
Der geofunn "Snøhetta" ist eigentlich ein nordryggstien-geofunn, d.h. der sollte das neue Symbol haben in der Preview:
![screen shot 2015-04-15 at 10 00 51](https://cloud.githubusercontent.com/assets/7487883/7154434/6a18c2ea-e356-11e4-9e58-70f81e2cc10c.png)

**Comment by lukassiedel** [comment]
fixed

**Comment by diplomod** [comment]
top, läuft
