### ISSUE TITLE
geofun view non existing

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#14]
This view is not available yet:
![screen shot 2015-02-09 at 09 28 50](https://cloud.githubusercontent.com/assets/7487883/6102933/3fbf0086-b03e-11e4-84b1-e381619099af.png)

Should look like this:
![04_nordyggen_geofun_wordpress_comments](https://cloud.githubusercontent.com/assets/7487883/6102940/4e9e8c0c-b03e-11e4-8ef2-76ba65ea52ad.jpg)

**Comment by bokiftw** [comment]
Can you explain me more this task, I am not informed. What is this page, where are you creating it and where and how do you want it to be displayed? Thanks.

**Comment by diplomod** [comment]
I believe we had this oage already working, but I can't find it any more. I would like to see the realized page where we show a geofunn in details (like in the design)

**Comment by bokiftw** [comment]
Okay, here is the link of this page: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/en/geofunn/

It is not translated to the other languages but English, so it can be viewed only in English section.

**Comment by diplomod** [comment]
All right - got it, thanks. I'll start translating tonight
