### ISSUE TITLE
Change format of coordinates on home

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#140]
We should show here the format in dgerees, minutes and seconds:

e.g. 59° 34' 39'' instead of 7.xxxxxxxxx

Who is in charge for this?
@Immoz or @bokiftw or @lukassiedel ?  

Thisis fairly urgent as we need to have it changed by Thursday  -next big meeting

**Comment by bokiftw** [comment]
As far as I remember I made it like the text field so user can type on his own. I would say it just up to user so there can be type whatever and however you want. However, if this value is taken automatically from the backend then it's not up to me :)

**Comment by diplomod** [comment]
Thanks for the info.
The input format can be chosen, that's correct. But the output format on the website should be as specified above.
@lukassiedel deine Baustelle?

**Comment by lukassiedel** [comment]
done :)

**Comment by diplomod** [comment]
Yo, passt, merci
