### ISSUE TITLE
Default Minuten-Format bei Koordinaten in Eingabe Geofunn

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#142]
Bei der Eingabe sollte das Default ausgewählt sein, damit die meisten Geofunn immer in dem Format in ie DB kommen:
![screen shot 2015-04-22 at 23 43 32](https://cloud.githubusercontent.com/assets/7487883/7286101/97bb4ef4-e949-11e4-8980-0601b3951549.png)

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
top!
