### ISSUE TITLE
Button in geofunn page to submission form does not work

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#143]
Missing link:
![screen shot 2015-04-23 at 00 41 48](https://cloud.githubusercontent.com/assets/7487883/7287066/9fead34e-e951-11e4-81d1-6a967cb8a7a2.png)

**Comment by bokiftw** [comment]
Okay I have fixed this. I made it static and it heads to the submit page, but in that case submit page must named "Submit" inside Wordpress, so take care that this is not changed.

Is that OK?

**Comment by diplomod** [comment]
I gess for now it serves the purpose. We do not intend to change the page's title. Thanks! please include in theupdate today.
