### ISSUE TITLE
Vorschläge bei der Suche in der Map werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#144]
Bisher war es so, dass die Suche in der Map breits während des Eintippens eines Suchbegriffs die Vorschläge unter der Suchzeile angezeigt hat - macht er nicht mehr...

**Comment by lukassiedel** [comment]
bei mir funktioniert das an sich. immoment ist allerdings die mindestlänge auf 3 zeichen eingestellt. das heißt eher fängt er nicht an zu suchen. und er scheint die daten etwas langsam abzurufen. ich werd mal mit dem @Immoz kommunizieren woran das liegen könnte

**Comment by diplomod** [comment]
ja, geht jetzt auch wieder bei mir. Evtl. war der Server wieder mal lahm.
