### ISSUE TITLE
Bike-Routen in anderer Farbe anzeigen

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#146]
Wir haben explizit 3 Bike-Routen auf dem Trail. 
Wenn ich diese als seperate KML Dateien schicke, kann man diese dann wie den E1 über das Menü zusätzlich anzeigen lassen, z.B. in Grün dann? Also alle auf einmal beim checken der Checkbox.

**Comment by lukassiedel** [comment]
ja ich denke das wär möglich das einzubauen

**Comment by diplomod** [comment]
OK, wäre wichtig. Hab 3 files, die dann zusammen angezeigt werden dürften.
Aber nicht default angezeigt, neue checkbox.

Name "NORDRYGGSTIEN PÅ SYKKEL"

Schicke ich per Mail.

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
Super - kannst du das Grün noch kräftiger machen? Schaut ein wenig transparent aus.

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
top
