### ISSUE TITLE
Change wording in map menu

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#147]
HYTTER => HYTTER LANGS NORDRYGGSTIEN

GEOFUNN => GEOFUNN I FJELLKJEDEN

Wird beides wohl zweizeilig, aber muss sein.
Geht das überhaupt?

**Comment by lukassiedel** [comment]
ja sollte gehen

**Comment by lukassiedel** [comment]
done. hab das layout gleich so angepasst, das es nicht überlappt und die 2 zeilen sich ordentlich darstellen

**Comment by diplomod** [comment]
top - merci

**Comment by diplomod** [comment]
Einen Type haben wir jetzt drin: 
Das sollte "ANDRE HYTTER" heißen:
![screen shot 2015-05-04 at 20 28 40](https://cloud.githubusercontent.com/assets/7487883/7459449/59db75ee-f29c-11e4-8155-9ef575f949c2.png)
