### ISSUE TITLE
Layout Format Koordinaten in geofunn Unterseite

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#149]
Hier auch bitte das Format verwenden: 63° 03’ 05’'
an Stelle von  Lat: 63.08338 Lon: 12.05707 verweneden

Siehe auch #148 

![screen shot 2015-04-27 at 17 02 06](https://cloud.githubusercontent.com/assets/7487883/7350366/279c394e-ecff-11e4-876e-21d6ea1d7698.png)

**Comment by lukassiedel** [comment]
bei den popups in der karte schätz würd ich das auch gleich mit machen

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
ah logo - danke, genau
