### ISSUE TITLE
Fjellheimer and Geologi Thumbnails have different hight

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#15]
Now the thumbnails ar all the same hight in the Geologi page, but when I switsch from Geologi to Fjellheimer, I realize that the thumbnails on these two sites have different hights.
The Thumbnails in Geologi are higher than the thumbnails in Fjellheimer.
They should be the same and in the hights as specified by Igor in the design:

![screen shot 2015-02-09 at 09 42 47](https://cloud.githubusercontent.com/assets/7487883/6103092/443e5196-b040-11e4-9eae-45a33ec9a2cb.png)
![screen shot 2015-02-09 at 09 42 52](https://cloud.githubusercontent.com/assets/7487883/6103091/443e6e4c-b040-11e4-9f14-836d6502cf54.png)

**Comment by bokiftw** [comment]
Sorry I didn't notice this bug, now it is fixed.
