### ISSUE TITLE
Hintergrundbild bei "Submit"

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#150]
Kann man hier ein Hintergrundbild einbauen, wie bei /map?
http://dokuhl.de/nordryggen/login/

Die Vorstellungen der Kollegen gehen in diese Richtung:
![unbenannt2](https://cloud.githubusercontent.com/assets/7487883/7414692/971dec66-ef54-11e4-8764-25ce8271dc9d.png)

Original Bild:
![forside 2](https://cloud.githubusercontent.com/assets/7487883/7414703/a69f04e0-ef54-11e4-8cc0-e93c15a9ecc2.jpeg)
Bitte darauf achten, dass es nciht ewig zum laden braucht - also gerne Qualität des Bildes auf ein Minimum runterschrauben.

**Comment by lukassiedel** [comment]
also wirklich bei submit einfügen schätz ich oder? weil im ersten bild die login seite gezeigt ist :)

**Comment by diplomod** [comment]
Geht beide?

**Comment by lukassiedel** [comment]
ja klar. hab ich mal in beide gemacht

**Comment by diplomod** [comment]
cool. Kannst du:
1) den Rand rechts und links von der Form noch schmäler machen, dami man mehr von dem Bild sieht?
2) Ein klein bissche Transparenz machen? :)
3) Das Bild tausche  mit dem hier:
![Uploading Fjellbakgrunn for nettsted.jpg…]()

**Comment by philipdomann** [comment]
Bild fehlt

**Comment by diplomod** [comment]
zefix...

![fjellbakgrunn for nettsted](https://cloud.githubusercontent.com/assets/7487883/7491216/82b006d2-f3e7-11e4-8e47-0cd9bb1666e2.jpg)

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
merci

**Comment by diplomod** [comment]
Chef will nochmal ein anderes Bild -siehe Email
