### ISSUE TITLE
Wording in Button auf home in English/Deutsch

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#152]
Englische Version soll heißen:
EXPLORE THE NORDRYGGEN TRAIL (also "GEO" raus)
![screen shot 2015-04-30 at 16 35 36](https://cloud.githubusercontent.com/assets/7487883/7415199/794348a0-ef57-11e4-89eb-003b23a69e11.png)

Deutsche Version das selbe:
ERFORSCHE DEN NORDRYGGEN TRAIL
![screen shot 2015-04-30 at 16 39 00](https://cloud.githubusercontent.com/assets/7487883/7415205/7e7396e0-ef57-11e4-9ae4-b3c401e838d6.png)

**Comment by lukassiedel** [comment]
done
