### ISSUE TITLE
Typo in submit

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#153]
Button ganz unten:
SEND INN DITT GEOFUNN
(ein "N" fehlt)

![screen shot 2015-05-01 at 21 21 25](https://cloud.githubusercontent.com/assets/7487883/7435898/5b21b950-f048-11e4-9b0b-5e95f475104d.png)

**Comment by lukassiedel** [comment]
ich finds grad nicht. auf welcher seite ist der button?

**Comment by diplomod** [comment]
submit - nach /login (du musst dich einmal einloggen)

**Comment by lukassiedel** [comment]
done
