### ISSUE TITLE
Trail & geofunn werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#155]
Irgendwas psst da nicht:

![screen shot 2015-05-03 at 18 46 02](https://cloud.githubusercontent.com/assets/7487883/7445855/b9811874-f1c4-11e4-89a7-879e2b861aa3.png)

**Comment by lukassiedel** [comment]
verdammt ich hab es auch grad gesehen. das muss beim letzten update passiert sein. ich schau mir das an sobald ich kann

**Comment by diplomod** [comment]
merci - morgen haben wir um 11 wieder eine wichtige Präsi. Da wäre es gut, wenn das geht. ;)

**Comment by lukassiedel** [comment]
gut habs gefixed. hatte beim letzten upload was übersehen. sorry für den schock :) und viel erfolg bei der Präsi

**Comment by diplomod** [comment]
easy - merci!
