### ISSUE TITLE
Submit: 2te Überschrift raus

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#156]
Den Satz brauchen wir nicht - bitte komplett entfernen. (Ich find's im Admin ned, anscheinend irgendwo verbaut)

"BESKRIV DITT NORDRYGGEN GEOFUNN"

Siehe hier: http://dokuhl.de/nordryggen/login/submit/?auth_name=Hans&auth_email=hans_gebauer%40hotmail.com

![screen shot 2015-05-03 at 19 02 12](https://cloud.githubusercontent.com/assets/7487883/7445928/16a169c6-f1c7-11e4-86f2-e57809da489b.png)

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
Merci. Kannst du noch den 2ten roten Strich rausnehmen? Sieht jetzt ohne Text komisch aus:
![screen shot 2015-05-10 at 09 47 48](https://cloud.githubusercontent.com/assets/7487883/7553444/a2990bfa-f6f9-11e4-8ac7-59a9bc3ee09c.png)

**Comment by lukassiedel** [comment]
gemacht :)
