### ISSUE TITLE
Nach Submit: 2 Buttons einbauen

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#157]
Nach dem Einreichen eines geofunn 2 buttons unter dem Text anzeigen.

Button 1: HOME

Button 2:

EN: SUBMIT ANOTHER GEOSITE

NO: LEGG INN ENDA ET GEOFUNN

DE: WEITEREN GEOFUNN BEITRAGEN

Bei Button 2 dann die Email Adresse übernehmen - also kein Login nötig

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
Super.

Kannst du da noch ein wenig mehr Platz darunter einbauen? Wirkt etwas gedrängt, v.a. mit dem Hintergrundbild.

![screen shot 2015-05-10 at 10 06 28](https://cloud.githubusercontent.com/assets/7487883/7553504/60a53ebe-f6fc-11e4-8fa2-e5254a71df4b.png)

**Comment by lukassiedel** [comment]
gemacht. sollt schon oben sein

**Comment by diplomod** [comment]
läuft - merci
