### ISSUE TITLE
Where can I edit the links?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#16]
I don't find in admin where I can edit the links of these buttons:

![screen shot 2015-02-09 at 09 39 50](https://cloud.githubusercontent.com/assets/7487883/6103102/628f8642-b040-11e4-8807-537f6f1ceac4.png)
![screen shot 2015-02-09 at 09 39 54](https://cloud.githubusercontent.com/assets/7487883/6103103/62907980-b040-11e4-8ebd-2cba53c66a80.png)
![screen shot 2015-02-09 at 09 40 00](https://cloud.githubusercontent.com/assets/7487883/6103104/62925930-b040-11e4-92e8-c25fde7bbbea.png)

**Comment by bokiftw** [comment]
When you are editing About page (Welcome to nordryggen) you will see URL fields under the editor.
![screen shot 2015-02-09 at 13 38 36](https://cloud.githubusercontent.com/assets/5833593/6106380/35c84fb0-b061-11e4-9b34-0af9362b0f0c.png)

There is a description for each. Content links (left and right) are these under the text. Side links are for buttons on the right side (kart, nyheter, etc..) and last one is for big red button.

**Comment by diplomod** [comment]
Excellent, thanks
