### ISSUE TITLE
Weißen Rand bei geofunn Preview auf map reduzieren

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#160]
Kann man da den Rand etwas geringer machen? Da wird auf der map ganz schön viel Platz verbraten:

![screen shot 2015-05-04 at 21 33 11](https://cloud.githubusercontent.com/assets/7487883/7460695/4cfbfcdc-f2a5-11e4-9709-427e4750d588.png)

**Comment by diplomod** [comment]
jetzt hat's was:
![screen shot 2015-05-08 at 12 16 25](https://cloud.githubusercontent.com/assets/7487883/7534576/1fd6ed46-f57c-11e4-9a60-a44c5482c621.png)

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
Danke. Geht noch ein wenig mehr - also noch weniger - weisser Rand? Vielleich auch einen Ticken weniger Brit - also generell kompakter?
Siehe auch #68

**Comment by lukassiedel** [comment]
ist gemacht. die breite konnt ihc nur ein kleines stück verringern weil sonst die überschriften (wenn zu lang) runter rutschen und das alles zerschießt. da müsste man nochmal schauen ob man dafür die anordnung ändert

**Comment by diplomod** [comment]
OK. Schriftgrüße bei der Überschrift kleiner?

**Comment by lukassiedel** [comment]
können wir machen aber ich glaub das muss wie gesagt eh nochmal überarbeitet werden. der kurzbeschreibungstext ist teilweise auch zu lang, so dass da bei manchen auch was verrutscht hab ich vorhin gesehn

**Comment by diplomod** [comment]
den kurzbeschreibungstext kannst du eigentlich kicken - wenn das einfach geht.
