### ISSUE TITLE
"GEOLOGISKE KATEGORIER" wieder oben ausrichten

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#168]
Das ist wieder nach untn gerutscht mit dem letzten Update:

![screen shot 2015-05-06 at 12 10 08](https://cloud.githubusercontent.com/assets/7487883/7491350/fca17bd2-f3e8-11e4-9ffe-d4a5f767cae7.png)

**Comment by lukassiedel** [comment]
done
