### ISSUE TITLE
Map 

### ISSUE THREAD

**Issue by bokiftw** [diplomod/nordryggstien.no#17]
Can you please send me a link where I can see working example of the map? I need to check something for elements html structure. It can be also demo from the plugin page, just to see the same map you will use on the site.

**Comment by diplomod** [comment]
Hi - it could work like this one: http://ut.no/kart/

I'll also check with the guys who are going to program the map

**Comment by bokiftw** [comment]
Static map elements (sidebar and popup) are finished. You can take a look at home page.

Also, pins are simple images called: geologi_pin_icon.svg, hytter_pin_icon.png, nordryggsean_pin_icon.svg. They are in the images/icon/ folder and they just need to be imported when generating the pin in map view. Now I can't do anything more with it.

**Comment by diplomod** [comment]
OK, looks already like we're going in the right direction.

It seems a little too big/not in proportion, but let's see how it is when the functionalities are included. Eventually Igor can check.
