### ISSUE TITLE
Typo in Links auf Infopages "SE EXEMPLER"

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#170]
Das ist falsch:

![screen shot 2015-05-07 at 12 08 25](https://cloud.githubusercontent.com/assets/7487883/7513210/bdf04524-f4b2-11e4-9900-25407c86ac04.png)

Muss "SE EXEMPLER" heissen - E statt A

**Comment by bokiftw** [comment]
I think this is up to me, so will send an update on this to Lukas.

**Comment by diplomod** [comment]
many thanks!

**Comment by lukassiedel** [comment]
done
