### ISSUE TITLE
Link am Ende der geofunn Sub-Page falsch

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#171]
Der verlinkt auf irgend was komisches, jedenfalls nicht die Karte. Z.B. http://dokuhl.de/nordryggen/?focusID=3293
Ist bei jedem geofunn anders.

![screen shot 2015-05-07 at 15 12 43](https://cloud.githubusercontent.com/assets/7487883/7515947/caf4d366-f4cb-11e4-8340-5c75ca7b256a.png)

Sollte auf die Map verlinken

Siehe zB http://dokuhl.de/nordryggen/geofunn/migmatitt-pa-lindesnes/ 

Außerdem ist das in der norwegischen Version Englisch...

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
Funktioniert - nur ist der Link jetzt falsch geschrieben. Das müsste "SE ALLE PÅ KARTET" heissen. (es fehlt also ein E bei "ALLE"), aber ich finde das nicht im String Translation Tool.

![screen shot 2015-05-10 at 09 56 26 1](https://cloud.githubusercontent.com/assets/7487883/7553466/f67adbd0-f6fa-11e4-9f07-8134e402be80.png)

**Comment by lukassiedel** [comment]
erledigt
