### ISSUE TITLE
Remove intro on home

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#172]
We realize that for many pistures on home (slider), the intro is very hard to read becaue of a lack of contrast.
As it is almos impossible to select the pictures according to the colour at the spot of the intro, we want to remove the intro on the home slider (not only on smartphones and tablets, but also on desktop & laptop etc.).

Can this be done eaily?

**Comment by bokiftw** [comment]
Done.

**Comment by diplomod** [comment]
thanks a lot for all the updates. I need to check them on the new server - just right now there is some mix-up, so I wait until tomorro to go through. :)

**Comment by diplomod** [comment]
works on nordryggstien.no - thanks
