### ISSUE TITLE
Preview und Button "VIS NORDRYGGSTIEN ..." rechts oben beissen sich

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#173]
Das haut nicht hin:
![screen shot 2015-05-08 at 10 24 15](https://cloud.githubusercontent.com/assets/7487883/7533636/676c1d6a-f573-11e4-90ab-996a1de39ee1.png)
Die preview muss immer außerhalb des buttons bleiben.
siehe auch #160

**Comment by lukassiedel** [comment]
sollte sich jeztt nicht mehr behindern

**Comment by diplomod** [comment]
schaut gut aus
