### ISSUE TITLE
ANDRE HYTTER wieder HUTS

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#175]
Das hatten wir schon mal:

![screen shot 2015-05-10 at 09 36 10](https://cloud.githubusercontent.com/assets/7487883/7553419/2a545fa6-f6f8-11e4-8ac4-5547987bea04.png)

muss ANDRE HYTTER heissen

BTW: In dem String tranlastion Ding stimmt es. Hängt das nicht zusammen?
![screen shot 2015-05-10 at 09 36 03](https://cloud.githubusercontent.com/assets/7487883/7553421/44593f0c-f6f8-11e4-9c25-818c4b67725c.png)

**Comment by lukassiedel** [comment]
erledigt
