### ISSUE TITLE
Map on the submission window + Autocomplete

### ISSUE THREAD

**Issue by arimkus** [diplomod/nordryggstien.no#179]
Suggestion about Geofunn submission process: the map in the submission form should also have all the geofunn items, like on the main map. Would be easier to avoid duplicate entries this way if people who submit already see that the same location is already on nordryggstien.

**Comment by diplomod** [comment]
very good point.
Also: Is it possible to have an autocomplete in the title?

**Comment by diplomod** [comment]
Lassen wir erst mal- lieber was doppelt
