### ISSUE TITLE
Language selection font size

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#18]
The font in the dropdown seems very small compared to the foint of the selcted language

![screen shot 2015-02-12 at 16 06 51](https://cloud.githubusercontent.com/assets/7487883/6169959/44c8877e-b2d1-11e4-85f2-0a2ae37c5801.png)

**Comment by bokiftw** [comment]
Okay, I have put it a bit bigger. I guess now it is alright, you can check.

**Comment by diplomod** [comment]
yes, looks better now, thanks
