### ISSUE TITLE
Bilder von Geofunn von dokuhl auf Live holen

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#180]
Wir haben wärend des Umzugs auf Live noch ein paar Bilder geupdated bei geofunn:
Kannst du die von dokuhl einfacher rüberholen übder die DB als dass wir das nochmal machen?

http://nordryggstien.no/geofunn/lofoten/

http://nordryggstien.no/geofunn/trollfjorden-og-raftsundet/

http://nordryggstien.no/geofunn/ur-typisk-for-norske-fjell-2/

http://nordryggstien.no/geofunn/blokkmark-opp-mot-vesttoppen-snohetta/

http://nordryggstien.no/geofunn/blokkmark-pa-glittertind/

http://nordryggstien.no/geofunn/blokkmark-pa-vei-mot-galdhopiggen/

**Comment by lukassiedel** [comment]
ist gemacht :)

**Comment by diplomod** [comment]
merci
