### ISSUE TITLE
Bildergrößen: Doch Breite definieren

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#183]
Die Bilder sind nun teilweise arg klein, obwohl die Auflösung mehr hergeben würde:

![screen shot 2015-05-11 at 10 19 51](https://cloud.githubusercontent.com/assets/7487883/7560860/68b48b0c-f7c7-11e4-964f-10c5d76f7266.png)

Kann man vielleicht einen Mitteweg einschlagen und immer eine Mindestbreite anvisieren und dafür in Kauf nehmen, dass oben und unten etwas weggeschnitten wird? Aber halt nicht so radikal wie vorher, indem man auf die komplette Breite geht, sondern nur bis zu einem Maximalwert, z.B. die Breite des Contentbereichs?

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
Schaut gut aus. Ausrichtung des Bildes in der Höhe passiert über die Mitte, oder? Also nicht Orierntierung am unteren oder oberen Rand.

**Comment by lukassiedel** [comment]
ja das bild wird oben und unten gleich weggeschnitten

**Comment by diplomod** [comment]
Top!
