### ISSUE TITLE
Bildschirmgröße

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#184]
Ich habe ein Problem mit der Bilschirmgröße - evtl. liegt das an meinen Einstellungen, aber ich habe das Logo nun immer mehr oder weniger mitte im Screen, und nicht mehr am linken Rand.
Der Bereich am rechten Rand verhält sich genau so.
Gleiches Problem in unterschiedlichen Browsern (FF, Chrome, Safari). Raus- und Reinzoomen bringt nichts.

Es sollte ja zumindest auf einem Standard-Laptop (15'') schon die ganze Bildschrimbreite genutzt werden, auch für die Navi.

![screen shot 2015-05-11 at 10 27 38](https://cloud.githubusercontent.com/assets/7487883/7560959/60d158ce-f7c8-11e4-8691-7de79123bfb3.png)
![screen shot 2015-05-11 at 10 27 45](https://cloud.githubusercontent.com/assets/7487883/7560960/60d61260-f7c8-11e4-9134-474c60b2e6af.png)

Bei einem großen Bildschirm (z.B. 24'') sollte man nicht auf die ganze Breite gehen, das sieht dann auch wieder blöd aus.

(Alles Finetuning ;))

**Comment by lukassiedel** [comment]
ich glaub das war absicht, das das soweit eingerückt ist wie der restliche content aber das können wir gern wieder breiter ziehen. ich werd mich heut nachmittag darum kümmern

**Comment by diplomod** [comment]
denkbar... ich verlasse mich auch auf eure EMpfehlung. Aber grad am mittleren Schirm mit 15'' könnte man das weiter ausnutzen. Wenn es kein großer Act ist können wir das ja mal ausprobieren und schauen, wie es sich dann weiter verhält - nicht dass es dann bei kleineren Bildschrimen wieder was zerschiesst.
