### ISSUE TITLE
Map auf 24''

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#185]
Die Map wird auf einem großen Bildschirm nicht komplett eingesetzt, unten sieht man die Community, was eigentlich nicht sein sollte.

Kann man die Map hier komplett ausschöpfen?

![screen shot 2015-05-11 at 10 29 34](https://cloud.githubusercontent.com/assets/7487883/7561022/fdcee4c0-f7c8-11e4-888a-272178a330c0.png)

**Comment by lukassiedel** [comment]
kann ich grad nicht reproduzieren. auf meinem 24"er seh ich zwar unten auch einen kleinen weißen streifen aber nicht die ganze community. sieht aus als wärs bei dir weiter rausgezoomed die ganze anzeige

**Comment by diplomod** [comment]
ok - muss ich checken

**Comment by diplomod** [comment]
negativ - ist ein 27'' - Riesenteil. Das muss aber laufen. Könnt ihr das checken? Oder ist bei 24 Schluss?

**Comment by lukassiedel** [comment]
sollte jetzt auf jedem monitor exakt die volle größe ausschöpfen. aber testen müsstest du das^^ hab keine kinoleinwand da ;)

**Comment by diplomod** [comment]
Yo! 27'' rockt! Was super ist, weil wir nächste Woche auf der Konferenz das Projekt auf einem großen iMac am Stand präsentieren werden. Merci.
