### ISSUE TITLE
Probleme mit Map im IE

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#189]
Ein User hat mir berichtet, dass er im IE den Trail und die Geofunn nicht angezeigt bekommt - siehe Screenshot:

![11-05-2015 22-00-04](https://cloud.githubusercontent.com/assets/7487883/7581262/046b1b24-f881-11e4-9496-3471e4b18128.jpeg)

**Comment by diplomod** [comment]
Hier die Version:
![12-05-2015 18-15-29](https://cloud.githubusercontent.com/assets/7487883/7599119/ddb4f7d2-f8ff-11e4-9c4c-aa2983df1fa4.jpeg)

**Comment by lukassiedel** [comment]
ich hab es jetzt mla getestet indem ich mir IE version 10 und auch die 9 emuliert hab (das geht ganz gut inzwischen mit IE11. aber da hats mir auch den Trail angezeigt. ich werd nochmal suchen

**Comment by diplomod** [comment]
Bitte. Was kann es noch sein? Firewall? Komische Plugins? Scheiß Computer? Firmennetzwerk?

**Comment by diplomod** [comment]
@lukassiedel Habe gerade erfahren, dass es bei mehreren Firmen im Netzwerk nicht klappt, den Trail anzuzeigen. Was kann da sein? Siehe letzen Kommentar.

**Comment by philipdomann** [comment]
Wird wohl daran liegen, dass die Firmen JavaScript verbieten.

**Comment by diplomod** [comment]
Aha! Das ist blöd. Kann man das umgehen?

**Comment by lukassiedel** [comment]
Wenn die Firmen wirklich einen JS Blocker im Netzwerk haben kann man das nicht umgehen. Allerdings müsste dann reintheoretisch die Karte auch geblockt werden. Evtl. wird nur die Serverkommunikation blockiert, bei der der Trail und die Geofunn vom Server geladen werden. da weiß ich nicht ob es an bestimmten Zertifikaten liegt, die das netzwerk nicht zu lässt. da müsste ich nochmal recherchieren

**Comment by diplomod** [comment]
OK - lassenw ir das erst mal. Es sollte ja einigermaßen laufen. Danke.
