### ISSUE TITLE
Submission mit Geonova Account überträgt keinen Namen

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#192]
Bekomme eine Email ohne Namen, geofunn hat dann auch keinen Author:

![screen shot 2015-05-12 at 22 05 54](https://cloud.githubusercontent.com/assets/7487883/7597437/c8c9584c-f8f3-11e4-8354-a7451bbebd04.png)

**Comment by Immoz** [comment]
Ich hab grad nochmal einen Test-geofunn erstellt. Kam da die Mail richtig an? Im Adminbereich wurde der Geofunn inkl Namen auf jeden Fall erstellt.

**Comment by diplomod** [comment]
danke - hab dir die emails weiter geleitet mit info

**Comment by Immoz** [comment]
jetzt sollte es gehen

**Comment by diplomod** [comment]
merci - werde jetzt nicht testen, weil ich die anderen Prüfer nicht verwirren will. Aber passt sicher - merci
