### ISSUE TITLE
Submit & Email bei neuem Geofunn: Optimierung

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#196]
Submit: 
Alle Felder bis auf Tags & Hyperlinks verpflichtend (ich glaube, aktuell sind Bilder, Fjellheim, Geological Category und Geologiske attraksjoner nicht verpflichtend)
siehe #195 

Email:
In der Überschrift brauchen wir das  "... (review process)" nicht

Ich bekomme Mail ohne Autor und einem komischen Link - der ist ja normalerweise anders, oder? Also nicht .../?post_type=... sondern einfach nur der Titel des geofunn

![screen shot 2015-05-14 at 15 51 35](https://cloud.githubusercontent.com/assets/7487883/7632932/5c830cdc-fa51-11e4-85f3-8c0ec284b165.png)

**Comment by lukassiedel** [comment]
Review process hab ich ruasgenommen. der link wird ja von wordpress generiert und wird hier eigentlich genauso geholt wie überall anders auch. kann aber sein, das es durch das gerade erst geschehene anlegen den noch anders formatiert. ich schau mir das an aber an sich geht der link ja auch^^

**Comment by diplomod** [comment]
ok, passt. hauptsache man kommt zum Geofunn.
Zu klären sind dann nur der fehlende Name und das fehlende Intro
