### ISSUE TITLE
Search schließt andere Geofunn nicht mit ein

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#197]
Geofunn in der Kategorie "Andere Geofunn" werden von der Suche nicht gefunden. Auch in der Map nicht. Dürfte wegen mir schon sein.

**Comment by lukassiedel** [comment]
kann das sein das die zwar angezeigt werden aber bei der suche das icon von normalen geofunns kriegen?

**Comment by diplomod** [comment]
Korrekt - da wird das falsche Symbol angezeigt. Siehe Screenshot - die Preview zeigt einen anderen geofunn an
Kannst du das fixen?
![screen shot 2015-05-15 at 20 33 23](https://cloud.githubusercontent.com/assets/7487883/7659359/b1b54d82-fb41-11e4-89c5-580f1f6ac5a6.png)

**Comment by lukassiedel** [comment]
ja werd ich mir anschauen

**Comment by lukassiedel** [comment]
gut ist gemacht auch das mehrfache anzeigen gleich mit rausgenommen

**Comment by diplomod** [comment]
perfekt, läuft. merci

**Comment by diplomod** [comment]
siehe auch #194
