### ISSUE TITLE
Admin-Accounts

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#198]
Ich habe zwei User, welche sich schon einmal mit ihrem Geonova-Account angemeldet haben und damit in der DB stehen, zu Admins gemacht.

Die haben aber laufend Probleme, sich einzuloggen bzw. fliegen raus.

Gibt es da ein Problem, weil das irgend wie mit dem Submit-Modul zusammen hängt?

**Comment by philipdomann** [comment]
Vlt könnte ja de rein oder andere uns sein PW geben?

**Comment by diplomod** [comment]
lassen wir mal aussen vor - wenn weiter Probleme auftreten greifen wir das auf

**Comment by diplomod** [comment]
Tritt immer wieder auf - siehe auch #210
