### ISSUE TITLE
Comment löst Email an alle Geonova User aus

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#199]
Bitte sofort abdrehen - wie besprochen möchte ich aktuell keine Emails ausgelöst haben!
![screen shot 2015-05-14 at 21 18 19](https://cloud.githubusercontent.com/assets/7487883/7639804/f36f1514-fa7e-11e4-83ed-fd3d2936d4c1.png)

**Comment by diplomod** [comment]
#200

**Comment by Immoz** [comment]
Das sollte jetzt aus sein.

**Comment by diplomod** [comment]
passt, merci
