### ISSUE TITLE
Image switch slower

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#20]
The images switch too fast  - a little slower would be good. (I mean the speed of the image, not the duration how long it is shown).

![screen shot 2015-02-12 at 16 10 07](https://cloud.githubusercontent.com/assets/7487883/6170031/d27dcac0-b2d1-11e4-9148-4cf5cb43daf9.png)

**Comment by bokiftw** [comment]
This is done. I changed the transition slide speed and reduced it. You can check it out if it suits you. Now it is 1.5sec.

**Comment by diplomod** [comment]
perfect, thanks
