### ISSUE TITLE
Fehlermeldung nach Comment

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#200]
Geht nicht:
![screen shot 2015-05-14 at 21 22 38](https://cloud.githubusercontent.com/assets/7487883/7639862/72b77c76-fa7f-11e4-9b64-0ed5c2da8398.png)

**Comment by lukassiedel** [comment]
hab es grad sowohl auf dokuhl als auch auf nordryggstien, sowie angemeldet und unangemeldet probiert. hat mich richtig weitergeleitet zum kommentar

**Comment by diplomod** [comment]
ja, geht bei mir jetzt auch... komisch. Aber gut, soll es geben... :) Merci
