### ISSUE TITLE
Fjellheim wird falsch angezeigt

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#201]
Der Fjellheim dieses geofunn ist falsch angezeigt:
http://nordryggstien.no/geofunn/skaupsjoen-holmetjonene/

Im Adminbereich sehe ich, dass es richtig eingegeben wurde:
![screen shot 2015-05-14 at 21 20 57](https://cloud.githubusercontent.com/assets/7487883/7639849/50d5d152-fa7f-11e4-9409-50596f5c4a80.png)

Es müsste also "Hardangervidda" und nicht "Sor Trondelag" da stehen - da ist irgend wo der Wurm drin.

**Comment by lukassiedel** [comment]
done

**Comment by diplomod** [comment]
Merci. was war das Problem? Nur ein verdreher bei dem oder was generelles?
