### ISSUE TITLE
different Instagram plugin

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#203]
I am not very happy with the Instagram Plugin we're using respectively with the design.

I would like to see many more pictures and not in a row, but as a stream of tiles, with the latest on top and the older below.

Kind of like this:
![screenshot-1](https://cloud.githubusercontent.com/assets/7487883/7665562/d62975c2-fbbd-11e4-8d15-c396577c66e9.jpg)

I got the screenshot from this plugin:
https://wordpress.org/plugins/instagram-feed/

Can it be changed accordingly?

**Comment by diplomod** [comment]
The plugin we are currently using is not good. It always show the old stuff. We should list the pictures strictly chronological, latest picture first.

I used the plugin that I mentioned in my previous comments in this website myself:
http://www.ncs-exploration.com/recentadvances/

It's straight forward, no effects, just a chronological listing in tile format.

If you show me where to edit this, maybe I can do it myself?

**Comment by bokiftw** [comment]
Hey Hans, 

Sorry for replying a bit late. I will take care of this, give me a little time and I will figure out the best way to change this, and will contact Lukas to make the changes.

**Comment by diplomod** [comment]
thanks! Great - no immideate hurry, but I would very much appreciate if this is resolved.

**Comment by bokiftw** [comment]
I just had a little research about this issue and instagram plugins for wordpress. This plugin which you showed me, and few other which are good and hopefully works good and are like you want,  are not free. They are free for showing the images from user, but when you want to show images by #hashatg you need a license.. So I don't know what you up to..

**Comment by diplomod** [comment]
Thank you Borjan! Well, as I wrote in my comment above, I made it work easily without a license on our other website. So I suggest I try the same on nordryggstien.no after my vacations. I would try on a normal page. If it works, you replace the current plugin with the new one on the home page. If not and we do indeed need a license for some reason, I can get that probably.

**Comment by bokiftw** [comment]
Hm, you are right, I see. But this is what I saw when installed it:
![screen shot 2015-06-24 at 09 30 00](https://cloud.githubusercontent.com/assets/5833593/8324739/bde02998-1a53-11e5-89a1-d273a88ad43c.png)
Maybe you should send me the .zip file of the plugin which you have used. And yeah, this is so far the plugin I would say.. but let's figure out something

**Comment by diplomod** [comment]
I found out that the plugin does not exist anymore, at least you can't download and install it anymore to a wordpress site.
We close this issue for now, no time to quarrel with that.
