### ISSUE TITLE
Link to NGU page in Geologi

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#22]
please add the button "LES MER OM GEOLOGISK MANGFOLD..." (which links to www.ngu.no/geomangfold) between the thumbnails and the button "BIDRA DIN GEOFUNN..." - above the red line on http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/geologi/

![screen shot 2015-02-12 at 16 29 50](https://cloud.githubusercontent.com/assets/7487883/6170391/aed3554c-b2d4-11e4-8568-d63a435b60b4.png)

**Comment by bokiftw** [comment]
This is done.

**Comment by diplomod** [comment]
thanks
