### ISSUE TITLE
Geofunn is submitted twice

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#221]
I submitted a test geofunn, but it was submitted twice:

![screen shot 2015-07-20 at 09 59 14](https://cloud.githubusercontent.com/assets/7487883/8771819/21b2c2e2-2ec6-11e5-80f0-f94b3db1e50b.png)

Links were:
http://nordryggstien.no/geofunn/titel-test/
and
http://nordryggstien.no/geofunn/titel-test-2/

(the geofunn are deleted by now)

**Comment by bokiftw** [comment]
Hi,

again, it is about the submission of the Geofunn, and I have no idea really how this is implemented and how to check why it is posted two times. Maybe is was just a bug or so.. Please contact backend people about this..

**Comment by philipdomann** [comment]
laut Tom hast du anscheinend zwei Geofunns angelegt? kam das nochmal vor?

**Comment by diplomod** [comment]
Nein. Ich hab garantiert nur einen angelegt. Theoretisch könnte es vielleicht sein, das zufällig jemand zeitgleich einen mit dem selben Tte eingereicht hat, aber das würde mich sehr wundern.

Anyway, scheint ein singulärer Event gewesen zu sein.
