### ISSUE TITLE
Submission form does not take over line breaks

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#222]
When you enter a linebreak in the submission form, it is not taken over. The text appears as one long paragraph:

![screen shot 2015-07-20 at 21 56 10](https://cloud.githubusercontent.com/assets/7487883/8785800/74f906e6-2f2a-11e5-9e38-f8f9350a560c.png)

**Comment by bokiftw** [comment]
Can You please describe me better this, so I can take a look and figure out what's going on. Which form is this, where are you typing this, etc? Maybe bigger screenshot..

**Comment by diplomod** [comment]
Very well: 
When you enter a new geofunn in the submission form on http://nordryggstien.no/login/submit/, the linebreaks in the fields are not shown on the website. All is one paragraph:

View in admin area after submission:
![screen shot 2015-09-16 at 10 34 09](https://cloud.githubusercontent.com/assets/7487883/9901932/136c2aac-5c6b-11e5-9325-75312984ce5d.png)

View on website after submission:
![screen shot 2015-09-16 at 10 34 58](https://cloud.githubusercontent.com/assets/7487883/9901939/2b40f81a-5c6b-11e5-95a2-8218f7effb2d.png)

I had to make the linebreaks manually in the admin area:
![screen shot 2015-09-16 at 10 34 37](https://cloud.githubusercontent.com/assets/7487883/9901946/376aea2e-5c6b-11e5-99eb-c7cb630b4910.png)

The it looks ok in the website:
![screen shot 2015-09-16 at 10 35 18](https://cloud.githubusercontent.com/assets/7487883/9901959/46aa1d8e-5c6b-11e5-967a-843a61c4b2f8.png)

**Comment by bokiftw** [comment]
Can you please try again, and see what happens now? I changed some settings but not sure will it work. thanks!

**Comment by diplomod** [comment]
Thank you, but apparently it does not work yet:

![screen shot 2015-09-23 at 11 53 49](https://cloud.githubusercontent.com/assets/7487883/10042140/cf6018d0-61e9-11e5-8ea8-7d021686df28.png)

**Comment by bokiftw** [comment]
I am quite sure this works now. I contacted Lukas, and we implemented the solution so it is online now. Please test it.

**Comment by diplomod** [comment]
Yes, great, thanks.
![screen shot 2015-09-24 at 09 55 16](https://cloud.githubusercontent.com/assets/7487883/10068161/6ce37738-62a2-11e5-842f-1e1d13e0c1b2.png)
