### ISSUE TITLE
Link to Geologi and Fjellheimer in About

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#23]
Can you please add these to links on top of the links at the right hand side of the about text - same style as the buttons that are already there:

![screen shot 2015-02-12 at 16 33 50](https://cloud.githubusercontent.com/assets/7487883/6170452/1f300010-b2d5-11e4-8edf-3d604d5617d5.png)

![screen shot 2015-02-12 at 16 28 15](https://cloud.githubusercontent.com/assets/7487883/6170455/224f6330-b2d5-11e4-9e02-45d1690b46da.png)

On this page: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/about/ 

Note: You probably need a symbol - eventually Igor can help quickly

**Comment by bokiftw** [comment]
I have done this. You can check if I understood you correctly and take a look at the icons Igor has made.

**Comment by diplomod** [comment]
Yes it's correct. But it needs to be translated. Now it's English also in Norwegian and German version.

Norwegian:
GEOLOGI
FJELLHEIMER

German:
GEOLOGIE
BERGREGIONEN

**Comment by bokiftw** [comment]
I forgot to tell this is also finished.

**Comment by diplomod** [comment]
Thanks.

Can we have a destination tag like for the map also for the Nyheter?

So this link
![screen shot 2015-03-03 at 09 13 36](https://cloud.githubusercontent.com/assets/7487883/6458607/ba312dc8-c185-11e4-9199-0ea091957eb6.png)
goes here
![screen shot 2015-03-03 at 09 14 55](https://cloud.githubusercontent.com/assets/7487883/6458614/d6ba44a2-c185-11e4-80cf-6b621be3dd0e.png)

**Comment by bokiftw** [comment]
Well yes, you can use this link and put in the custom filed 'side_news_link' - http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/en/#news

In future it will be http://YOUR HOME PATH/#news

**Comment by diplomod** [comment]
great, works - thanks
