### ISSUE TITLE
Login - Button and captcha missing

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#24]
Option 2 has no button and no captcha:

Screenshot:
![screen shot 2015-02-12 at 16 53 03](https://cloud.githubusercontent.com/assets/7487883/6170864/ccacdd92-b2d7-11e4-9ce3-65592794b131.png)

Design:
![screen shot 2015-02-12 at 16 53 41](https://cloud.githubusercontent.com/assets/7487883/6170872/d827247a-b2d7-11e4-9d18-1ca93d95e068.png)

**Comment by bokiftw** [comment]
I really don't know how this happens. I just checked in all three browsers (safari, chrome, firefox) and can see captcha and the button. Also I tried on different laptops.

**Comment by diplomod** [comment]
It does work in Safari actually. In Chrome, I see the captcha frame, but no content.
Nothing in Firefox.

I have similar problems with other applications - so this may be a problem of my browsers (had an update of OS recently, sucks)

**Comment by bokiftw** [comment]
Yeah, this was confusing, but I am quite sure this works. I double checked on two different macines and different browsers. I suggest you to check if Javascript is enabled in your browser (I am sure it is) and delete caches, but that's only thing I have in mind.
