### ISSUE TITLE
Login to submission page

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#25]
Can't login anymore with the demo-account:

![screen shot 2015-02-12 at 16 58 36](https://cloud.githubusercontent.com/assets/7487883/6170977/8b7b6356-b2d8-11e4-8a21-4be367e1ce4d.png)

**Comment by bokiftw** [comment]
I guess this is some confusion, since you never could login to that form. That is just a view of the form with no functionalities yet. It need to be implemented through backend part, once it is connected to database. etc. So this is just a static part with validation and with no logic.

**Comment by diplomod** [comment]
ah - ok, thanks for the reminder

@Immoz This will be part of your tasks then, if I understand correct (concerns the interface with geonova.no)
