### ISSUE TITLE
Open Link to geonova.no in exra tab

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#26]
as all external links - always extra tab!

![screen shot 2015-02-12 at 17 00 10](https://cloud.githubusercontent.com/assets/7487883/6171009/b787635a-b2d8-11e4-83b1-7ab048282b48.png)

**Comment by bokiftw** [comment]
This is done. Also all the links in the footer are made to open in extra tab.

**Comment by diplomod** [comment]
thanks, works
