### ISSUE TITLE
Picture upload size check - wording

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#27]
The upload function is very smooth. It realized when a file is bigger then 3 MB, that's great.

However, it does not check if a picture is actually too small. I guess it is not possible. 

But then I suggest we write instead of "Min. resolution" better "Optimal resolution"

![screen shot 2015-02-12 at 17 04 50](https://cloud.githubusercontent.com/assets/7487883/6171171/9397f6d4-b2d9-11e4-86fe-3e961f8f0f54.png)
(Geonova_ipad is only 1280x853 px)

**Comment by bokiftw** [comment]
Yeah that's better, I have changed it to 'Optimal resolution'.

**Comment by diplomod** [comment]
OK, good
