### ISSUE TITLE
Submit Geofunn - check required fields

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#28]
All fields are required. Currently, I can submit an empty form

![screen shot 2015-02-12 at 17 20 20](https://cloud.githubusercontent.com/assets/7487883/6171523/75e94fc8-b2db-11e4-9337-21b7bb2a1b4b.png)

**Comment by bokiftw** [comment]
Now all fields are set to required and an empty form will not be submitted.

**Comment by diplomod** [comment]
Not quite - the fields "Geological Category", "Fjellheim" and "Tags" are not mandatory:

![screen shot 2015-02-13 at 15 59 05](https://cloud.githubusercontent.com/assets/7487883/6189239/72c6e0bc-b399-11e4-9924-ea632ecc7182.png)

![screen shot 2015-02-13 at 15 59 18](https://cloud.githubusercontent.com/assets/7487883/6189257/8553da50-b399-11e4-8126-0515066a6821.png)

**Comment by bokiftw** [comment]
OK, sorry somehow I missed tags to make required. But the thing about dropdown lists is that actually they are always submitted with their first choice (if not specified differently). So they are not empty, the first choice is default and makes it non empty. That is why they are behaving like they ar not required. That is the thing we unfortunately can't change

**Comment by diplomod** [comment]
OK - so I understand it is technically impossible to make it obligatory to change from the default (first) to any other? In that case we must make the firt choice something general like "(nordryggen)"
