### ISSUE TITLE
Take out "Step 2" in submission form

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#29]
There is no "Step 1" in the login page, so please take out the "Step 2" (but leave the headline):

![screen shot 2015-02-12 at 17 19 02](https://cloud.githubusercontent.com/assets/7487883/6171539/98a2d228-b2db-11e4-8903-2e34b1030413.png)

**Comment by bokiftw** [comment]
This is done, I have removed 'step 2'.

**Comment by diplomod** [comment]
Great, thanks
