### ISSUE TITLE
Link logo

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#3]
Click on logo leads to http://staging.blgrd.co/

**Comment by bokiftw** [comment]
This is fixed. Logo is now leading to the Home page of the corresponding site.

**Comment by diplomod** [comment]
OK - but that is the map at the moment, without the picture slider. Should definitely link here: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/

**Comment by bokiftw** [comment]
Actually logo is leading to exactly that link you have mentioned. I tested it, but what is the thing. Now, when map is simple .jpg image it loads much faster then bigger images and content like slider above. So, slider loads 1-2 seconds slower then map, maybe that is why you think there is no slider. 

When there will be an actual map, the time difference win not be that obvious.

**Comment by bokiftw** [comment]
Ok I see what you mean, there is some difference in pages depending on language. I am looking to fix this. For english language there is no this issue.

**Comment by bokiftw** [comment]
UPDATE: The problem was that no posts for Norwegian language or German was made. This home slider works with posts for exact language and there MUST be minimum two posts in order to slider works.
So, I just "translated" (made) these two posts to Norwegian language, and now they appear in slider.

_So, take care that there must be a minimum two posts for desired language for slider to work on page for that language._

**Comment by diplomod** [comment]
OK, got it. But: 1-2 seconds is a looooong time. Is it because of the server of the test environment or because of the page architecture/picture size? If the latter, we should try to get it faster for live.

**Comment by bokiftw** [comment]
It is generally because of internet connection and loading the data, another server won't help. But now this is improved, as much as it can be. It doesn't show the map, but white space just before loading the first image.

**Comment by diplomod** [comment]
OK, let's have have an eye on it on the live platform then
