### ISSUE TITLE
min. resolution for pictures in upload

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#30]
What is actually the mininmal/optimal resolution for pictures so they can be shown
- on the front page and
- in the gefounn detail view?

![screen shot 2015-02-12 at 17 26 07](https://cloud.githubusercontent.com/assets/7487883/6171689/6c1c75aa-b2dc-11e4-9949-0f76c1144644.png)
![screen shot 2015-02-12 at 17 26 14](https://cloud.githubusercontent.com/assets/7487883/6171691/70be6672-b2dc-11e4-87ce-9a626e31c520.png)

**Comment by bokiftw** [comment]
The minimal size I would say is 1440x900px. But it can happen to show a bit blurry on much larger screens. For the Geofunn detail view, you don't need to take care since Wordpress can crop images automatically and you can define image size which to use. But in general for Geofunn it doesn't need to be a big image.

**Comment by diplomod** [comment]
Then I suggest you change the wording in "submit" accordingly: 

![screen shot 2015-02-16 at 17 07 27](https://cloud.githubusercontent.com/assets/7487883/6215155/545370f2-b5fe-11e4-8353-c6ed004ab93f.png)

See also #27 

Re geofunn-view: But in geofunn we also have the image quite big on top. What's the minimum size here?

![04_nordyggen_geofun_wordpress_comments](https://cloud.githubusercontent.com/assets/7487883/6215135/2cafc9ba-b5fe-11e4-9f64-83ebe090ed75.jpg)

**Comment by diplomod** [comment]
Can you let me know the minimum resolution for the geofunn main image?

**Comment by bokiftw** [comment]
I would suggest you to use 1600px wide images for this full-width images. So basically every featured image which will go full width should be 1600px wide to look nice on extra large screens. Height is not that important.

**Comment by diplomod** [comment]
Ok, thanks

**Comment by bokiftw** [comment]
I would like to just mention here about images you upload. We said that 1600px would be optimal for upload, but also when you upload images you should try to compress them a little bit. 

You can use ImageOptim software or in Photoshop to "Save for Web". It will fast up a loading the page and also optimise it for mobile devices.

**Comment by diplomod** [comment]
Great, thanks for the hint. It appears to be fairly a lot as loading takes time.
