### ISSUE TITLE
Submit: Possibility to enlarge entry field for Geological Explanation

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#31]
The field is too small and can not be extenbded, only scroll bar:

![screen shot 2015-02-12 at 17 42 58](https://cloud.githubusercontent.com/assets/7487883/6172049/c77b9b2c-b2de-11e4-87a7-67b5ac2a3f6c.png)

What we need is this:
![screen shot 2015-02-12 at 17 44 37](https://cloud.githubusercontent.com/assets/7487883/6172058/d74b6532-b2de-11e4-8e8d-70d1ae90a90e.png)

**Comment by bokiftw** [comment]
This is fixed. I added ability to resize textarea vertically.

**Comment by diplomod** [comment]
Excellent.
Also the default size is very good.
