### ISSUE TITLE
Submit: Word count in GEOLOGICAL EXPLANATION does not work

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#32]
The limitation for the words does not work. If it cannot be limited to 300 words, I suggest we use the character limitation (which works fine in title and intro) and limit to 2000 characters.

**Comment by bokiftw** [comment]
Yeah, it can't count the words, so now I made it to work with characters. Like you said, max is 2000.

**Comment by diplomod** [comment]
Excellent.

Since the count is shown anyway, I suggest you take out the wording "(max. 300 words)". Otherwise it is confusing - too much different info.

![screen shot 2015-02-13 at 16 03 13](https://cloud.githubusercontent.com/assets/7487883/6189315/f4e33dd4-b399-11e4-8af6-e5db5f7d4789.png)

**Comment by bokiftw** [comment]
OK, I removed this.
