### ISSUE TITLE
Submit - green background of headline

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#33]
When I had an error message during submit because a mandatory field was not filled out and I submit after I have filled the required information, I get this background of the headline of the thank you message.

This is ugly and not necessary.

![screen shot 2015-02-13 at 15 57 52](https://cloud.githubusercontent.com/assets/7487883/6189285/b98d5ba2-b399-11e4-9e60-021fb051c2fd.png)

**Comment by bokiftw** [comment]
This was the plugin default styling, so it is fixed now. It displays just the message upon submission.

**Comment by diplomod** [comment]
OK, thanks
