### ISSUE TITLE
Forms in English language

### ISSUE THREAD

**Issue by bokiftw** [diplomod/nordryggstien.no#35]
I would like to ask you if you have changed something so this plugin Forms is shown in Norwegian language in the sidebar?
![screen shot 2015-02-16 at 16 08 54](https://cloud.githubusercontent.com/assets/5833593/6214087/56e0b814-b5f6-11e4-86d6-6efe521b0484.png)

I have some issues so I think that is a problem and also difficulties to understand. So can you somehow get this back to English? Thanks!

**Comment by diplomod** [comment]
Nope - I have not seen it before in English, and I have not made any changes.
I was wondering myself.

**Comment by diplomod** [comment]
Is this clarified now?

**Comment by Immoz** [comment]
I fixed this on my local machine by changing "Admin language" to "EN" in admin-settings: WPML -> Languages -> Admin language
