### ISSUE TITLE
Direct link to map

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#37]
Is there a way how I can directly link to the map?
(I need it for the links in the sidebar)

![screen shot 2015-02-16 at 17 14 40](https://cloud.githubusercontent.com/assets/7487883/6215274/53abb582-b5ff-11e4-95f7-7f362aeeaa0f.png)

![screen shot 2015-02-16 at 17 10 13](https://cloud.githubusercontent.com/assets/7487883/6215275/57a00fee-b5ff-11e4-9611-103721c24e2d.png)

**Comment by bokiftw** [comment]
Would you like to show just map on the Home page? Link for that? Or you need exact link to the map of the current Geofunn with pin and info?

**Comment by diplomod** [comment]
For now only a link to an anchor or something - a way how I can link to the map (even though it's currently just an image)

**Comment by bokiftw** [comment]
you can use this link to map anchor - http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/#map

Of course you will have to change this since domain name and server is changed.
