### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#38]
External links should always be opened in a new tab.

In "About", these ones should open in a new tab:
- NORDRYGGEN NEW
- COMMUNITY
- READ MORE ABOUT NORDRYGGEN ON GEO365.NO
- READ MORE ABOUT THE GEOLOGICAL DIVERSITY ...

These should open in the same tab (content within the same project):
- ABOUT NORWAYS MOUNTAIN REGIONS
- MAP

**Comment by bokiftw** [comment]
This is done.

**Comment by diplomod** [comment]
Thanks. This link is not working yet.
It should link to http://www.ngu.no/emne/geologisk-mangfold 

![screen shot 2015-02-17 at 21 51 31](https://cloud.githubusercontent.com/assets/7487883/6237015/995874ee-b6ef-11e4-87f9-6f012a59e734.png)

**Comment by bokiftw** [comment]
OKay, I have fixed this. Link is now set. Anyways, you can always edit this link inside Wordpress admin.
![screen shot 2015-02-18 at 15 19 17](https://cloud.githubusercontent.com/assets/5833593/6248641/cfcba158-b781-11e4-8882-149d24d6c626.png)

These two fields are for these left and right buttons.

**Comment by diplomod** [comment]
Great.

There is a chance that this preference (which link shuld open in the same and whcih in an extra tab) changes. Is there a way to edit this?

**Comment by bokiftw** [comment]
Well it is, but only inside the code. It is easy but it has to be done inside the code.
