### ISSUE TITLE
About - Reduce hight of picture

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#4]
We should reduce the hight of the picture in about - on smaller laptob screens, you don't see the headline (this is 1280x800):

![screen shot 2015-01-23 at 17 10 25](https://cloud.githubusercontent.com/assets/7487883/5877844/daab376e-a322-11e4-941c-49ab2a724cab.png)

**Comment by bokiftw** [comment]
This view is fixed. Works similar to Home page, where picture is always the same hight of the browser, but heading and white space are going up more, so it can be seen when page is loaded. I guess that is fine.

**Comment by diplomod** [comment]
Yes, works very elegant, thanks.
However, the readers may not understand that they must scroll (don't ask - we are talking about 50+ year old geologists to some extend).
Can we integrate an arrow here next to the headline, pointing down?
![screen shot 2015-01-26 at 15 57 39](https://cloud.githubusercontent.com/assets/7487883/5901627/31a30bb6-a574-11e4-91d6-00e94bd441b8.png)
maybe we need Igor's support here.

**Comment by diplomod** [comment]
Actually, I believe we must reduce the hight of the picture. ALso in the geofunn-pages, I don't get it that the content is so far below:
![screen shot 2015-01-26 at 16 02 30](https://cloud.githubusercontent.com/assets/7487883/5901710/dec1ca9e-a574-11e4-8dbd-7e134f4977ef.png)

**Comment by bokiftw** [comment]
Okay, now this should be fixed on both pages. I guess now it fine and that enough of content is shown.

**Comment by diplomod** [comment]
Better, thanks. I also asked Igor if he has an idea to improve this - let's see if he has further input.

**Comment by bokiftw** [comment]
I did this with him, he agreed on this solution and we tested it. It shows correctly on other screens and looks nice.

**Comment by diplomod** [comment]
OK
