### ISSUE TITLE
Button to login/submit in Geology/Mountain Regions

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#40]
This button should link to the login page:

![screen shot 2015-02-16 at 18 50 46](https://cloud.githubusercontent.com/assets/7487883/6216724/dcad6b7a-b60c-11e4-9d76-849e204b3de2.png)

**Comment by bokiftw** [comment]
Okay, this is fixed.

**Comment by diplomod** [comment]
works, thanks
