### ISSUE TITLE
Adjust heading in submit for Geocoordinates

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#41]
Please change the heading for the geo coordinates as follows:

"GEO KOORDINATER (N)" => "GEO KOORDINATER (LATITUDE)"

"GEO KOORDINATER (E)" => "GEO KOORDINATER (LONGITUDE)"

and accordingly in the other languages (latitude and longitude are written the same in Norwegian, English and German)

![screen shot 2015-02-17 at 13 19 56](https://cloud.githubusercontent.com/assets/7487883/6228123/44c6d688-b6a8-11e4-9545-6e69216098c2.png)

**Comment by bokiftw** [comment]
Did this.

**Comment by diplomod** [comment]
Thanks!
@Immoz As dicssued - FYI
