### ISSUE TITLE
Symbol for geofunn in the map

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#42]
@Immoz 
We have a new symbol for geofunn in the map:

![screen shot 2015-02-17 at 17 57 34](https://cloud.githubusercontent.com/assets/7487883/6232786/b3801690-b6ce-11e4-842e-41686fb3989b.png)

Source is an official guideline by Norwegian map authorities:
http://www.kartverket.no/Documents/Standard/Bransjestandarder%20utover%20SOSI/symbol.pdf
(see page 16)

Can we use it and in what format do you need it?

ALso, there are other symbols (e.g. waterfall etc.) which may be relevant later. Can these be added, too?

**Comment by diplomod** [comment]
Can we therefore work with the categories/tags in admin when creating a new post (geofunn)?

![screen shot 2015-02-17 at 19 45 19](https://cloud.githubusercontent.com/assets/7487883/6234752/9c2abb3a-b6dd-11e4-9c42-36936547b310.png)

**Comment by diplomod** [comment]
FYI: I aksed Michael if they can provide a graphic file for this new symbol

**Comment by Immoz** [comment]
Yes we could work with categories and show specific markers on the map.

**Comment by diplomod** [comment]
Sehe gerade, dass die neuen Symbole scho eingebudnden sind.

Die nicht trail-relevanten aber bitte wieder mit den alten Symbolen

**Comment by diplomod** [comment]
Danke - die "Andre Geofunn" haben das falsche Symbol jetzt - den Wanderer in Weiß:

![screen shot 2015-03-30 at 09 03 18](https://cloud.githubusercontent.com/assets/7487883/6891464/bbc192e0-d6bb-11e4-97a3-474e16c2231c.png)

Das haut nicht hin.

**Comment by Immoz** [comment]
Kannst du auch hier nochmal versuchen den Browser-Cache zu leeren? Eigtl. sollten die richtigen Symbole angezeigt werden.

**Comment by diplomod** [comment]
Yo, geht. Aber: Link zu "Les mer" geht nicht...

**Comment by Immoz** [comment]
Habs grad getestet und bei mir läufts. War das evtl nur bei nem bestimmten?

**Comment by diplomod** [comment]
Also im Safari krieg ich das nicht hin mit dem neuen Symbol. Scheiss Apple... Dafür geht der Link. Firefox ght jedenfalls das Symbol... ird schon passen
