### ISSUE TITLE
Optimal resolution for Fjellheim pictures

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#43]
What is the optimal resolution for these pictures?
(Detail view image slider)
![screen shot 2015-02-17 at 18 29 25](https://cloud.githubusercontent.com/assets/7487883/6233432/16af8e40-b6d3-11e4-8326-7ba388d6d05f.png)

**Comment by bokiftw** [comment]
I would say 1024x768 is more than enough. So you can keep that, no need to be bigger.

**Comment by diplomod** [comment]
Thanks. I actually tried with 711x474 and seems to work fine.
