### ISSUE TITLE
Fjellheimer: Can't edit the links

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#44]
I have placed links but they don't work - when I click those buttons, I only get to the overview of the fjellheimer
![screen shot 2015-02-17 at 18 35 29](https://cloud.githubusercontent.com/assets/7487883/6233543/e0256cea-b6d3-11e4-94dc-9d9f792046e3.png)
![screen shot 2015-02-17 at 18 35 19](https://cloud.githubusercontent.com/assets/7487883/6233555/e383ba86-b6d3-11e4-8cc5-52a3b5fc714d.png)

**Comment by bokiftw** [comment]
Sorry, this was a bug. Now it is fixed, links work.

**Comment by diplomod** [comment]
Yes, works. Thanks.
