### ISSUE TITLE
Fjellheimer: Translation does not work since info is in picture captions

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#45]
Is there a way how we can translate the caption for each language?

The problem is that the info displayed in the slider is sourced from the captions of the pictures. So I need to upload the same pictures for each language with translated captions.

Is there a more elegant way to achieve this?

![screen shot 2015-02-17 at 18 39 54](https://cloud.githubusercontent.com/assets/7487883/6233641/a90dca3a-b6d4-11e4-98a8-035b9e8ebcd7.png)

**Comment by bokiftw** [comment]
Okay, for this there is a plugin which I have installed. It takes every media(image) and reference to it two other for different languages.

Here is the info and docs -  http://wpml.org/documentation/getting-started-guide/media-translation/

**Comment by diplomod** [comment]
OK - I guess it works. I'll try to make it work.
