### ISSUE TITLE
Fjellheimer: Text fields relevant?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#46]
Are these field relevant in any way?
![screen shot 2015-02-17 at 18 44 08](https://cloud.githubusercontent.com/assets/7487883/6233716/35d506cc-b6d5-11e4-9cfc-5eea08221714.png)

![screen shot 2015-02-17 at 18 44 29](https://cloud.githubusercontent.com/assets/7487883/6233718/397fe058-b6d5-11e4-9c7b-87a9a75e458e.png)

Any input I put is not shown anywere.
If it is useless, please take out, less confusion.

**Comment by bokiftw** [comment]
Headline is important. It the name of that post/fjell. I removed the editor and headline, we don't need that.

**Comment by diplomod** [comment]
great, thanks - better now
