### ISSUE TITLE
Fjellheimer: How to change map?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#47]
This seems to be fixed:
![screen shot 2015-02-17 at 18 44 54](https://cloud.githubusercontent.com/assets/7487883/6233740/6b311af4-b6d5-11e4-9b95-9c63e1d68d39.png)

is this related to this field? (which also does not work for me):
![screen shot 2015-02-17 at 18 47 12](https://cloud.githubusercontent.com/assets/7487883/6233751/79838ccc-b6d5-11e4-8c92-7375694fb31e.png)

**Comment by bokiftw** [comment]
Now I just removed that static image of the map which was over the text. I implemented that field for pasting the embed code for map. I am not sure how the backend guys will implement that, but anyways now that field is linked and you will see content which you put there.

**Comment by diplomod** [comment]
Got it - works.
Is it possible to have a WYSIWYG editor here so we can also put different content here, not only code for the map?

![screen shot 2015-02-18 at 17 56 22](https://cloud.githubusercontent.com/assets/7487883/6252001/8441b900-b797-11e4-9f66-29e417e98b34.png)

**Comment by bokiftw** [comment]
OK, I put here a WYSIWYG editor.

**Comment by diplomod** [comment]
thanks
