### ISSUE TITLE
Login page translation

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#48]
This page needs translation. Can I do it?

http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/de/login/

**Comment by bokiftw** [comment]
These plugins need to be translated via other plugin (WPML plugin), like I did submit page. So will do that, but again problem is that they have some conflicts. So I suggest to wait a bit. Meanwhile you can write me here the translations.

**Comment by diplomod** [comment]
OK - let's hope this is resolved soon.

The translation is in the Excel I have sent by Michael. Should all be there. Let me know if you need the doc again.

**Comment by diplomod** [comment]
What is the status on this?

**Comment by bokiftw** [comment]
Sorry I forgot to write you about this, but in the excel file all translations for this page are in english. SO I thought you wanted to keep all in English language.
![screen shot 2015-03-13 at 11 18 17](https://cloud.githubusercontent.com/assets/5833593/6636715/f75f7eda-c972-11e4-96b2-9402f2e7af7b.png)

Please, provide me the desired translations for this page. You can type it here and I will change this.

**Comment by bokiftw** [comment]
Can you please provide the translation soon, so I can do all changing in a row?

**Comment by diplomod** [comment]
Apparently I must have forgotten this - my apologies.

I cannot provide the translations right now, but we can leave it in English for the moment. However: You need to set the languages correct - even if we have it all the same. The problem at the moment is that the submission pages are only accessable in Englisch at the moment - the language changes to default English when I click on "Legg in geofunn" or "Geofunn beitragen"

**Comment by bokiftw** [comment]
Okay, I have fixed this. Now it doesn't switch to English automatically.

**Comment by diplomod** [comment]
OK - will review after next update, thanks!

**Comment by diplomod** [comment]
So far it does still... can you tell @Immoz which file is the relevant one so he can check whether it was transferred correctly

**Comment by diplomod** [comment]
@lukassiedel Bitte das mal anschauen - hier fehlt das zweite "N" in der Überschrift und wir kriegen das nicht in den Griff:
http://dokuhl.de/nordryggen/login/
