### ISSUE TITLE
De-activate auto-slider in fjellheimer

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#49]
The images shall not slide themeselves, users must click on the pictures below actively

![screen shot 2015-02-17 at 20 12 37](https://cloud.githubusercontent.com/assets/7487883/6235273/86c77cca-b6e1-11e4-88a4-c417f1dedd4e.png)

It's annoying because it slides while you read the text

**Comment by bokiftw** [comment]
Done.

**Comment by diplomod** [comment]
Thanks, appreciated. Much more relaxed experience now ;)
