### ISSUE TITLE
Tab jumps to 2nd form, not 2nd line in 1st form

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#5]
When I enter my email in the first line in the first form on this page and I click Tab, I get to the first line in the 2nd form on the page, not the 2nd line in the first form:

![screen shot 2015-01-23 at 17 13 19](https://cloud.githubusercontent.com/assets/7487883/5877900/3287526a-a323-11e4-84d4-f7a4e0ca26de.png)

**Comment by bokiftw** [comment]
Tabindex bug fixed.

**Comment by diplomod** [comment]
Works, thanks.
