### ISSUE TITLE
Fjellheimer: Detail view image slider not mandatory

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#50]
Can we take out that it is mandatory to add more pictures here?

![screen shot 2015-02-17 at 20 37 31](https://cloud.githubusercontent.com/assets/7487883/6235737/e5ca17f2-b6e4-11e4-9c9a-00ba2a24d28f.png)

**Comment by bokiftw** [comment]
Okay. I changed this also in the Geology image slider. It's not mandatory anymore.

**Comment by diplomod** [comment]
Great - so we can have a new mountain region or geological category if we have only one picture. Thanks!
