### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#51]
When I search, e.g.
![screen shot 2015-02-17 at 20 46 17](https://cloud.githubusercontent.com/assets/7487883/6235884/1f83011a-b6e6-11e4-8ed2-34dca02b6285.png)
I get this:
![screen shot 2015-02-17 at 20 46 10](https://cloud.githubusercontent.com/assets/7487883/6235887/246bb0dc-b6e6-11e4-84e4-dbfb1d7fa594.png)

**Comment by bokiftw** [comment]
Search is now fixed and works. It finds post and pages. But the thing is that, page with the search results wasn't in the design and it is not stiled correctly. Now it is just a page with results like a plain text.

**Comment by diplomod** [comment]
OK - I see. Haven't thought about it.

Suggestion: Can you layout a little bit so it looks presentable?
E.g. the search box should not be on the side of the screen (without any margin) but on top of the results (like in google)
![screen shot 2015-02-18 at 17 44 27](https://cloud.githubusercontent.com/assets/7487883/6251789/34f10f8c-b796-11e4-8822-140c8b980887.png)

This is not needed:
![Uploading Screen Shot 2015-02-18 at 17.48.23.png . . .]()

Also, search results are ok from my first impression, but when I click on one, I don't get to the actual post:
![screen shot 2015-02-18 at 17 47 25](https://cloud.githubusercontent.com/assets/7487883/6251792/3f77475a-b796-11e4-83ad-e951a9cd5c1c.png)

**Comment by bokiftw** [comment]
I have styled search result a bit. Please take a look.

**Comment by diplomod** [comment]
fine. If we could have pictures included somehow would be great.

**Comment by bokiftw** [comment]
I have implemented to show featured image under the post/page in search results. If there is a text, it will be shown next to the image.

**Comment by diplomod** [comment]
Works for Geofunn, this is great.

Can we also make it work for Geologi-Pages and Fjellheimer-pages,
e.g. this one:
![screen shot 2015-03-03 at 09 18 50](https://cloud.githubusercontent.com/assets/7487883/6458655/680eeb38-c186-11e4-999f-6098fbf2fde6.png)

**Comment by bokiftw** [comment]
As long as you define the featured image it will display. Welcome page didn't have featured image selected.
![screen shot 2015-03-03 at 09 40 15](https://cloud.githubusercontent.com/assets/5833593/6458930/aed68456-c189-11e4-8fcf-8c3c5199704b.png)

![screen shot 2015-03-03 at 09 40 53](https://cloud.githubusercontent.com/assets/5833593/6458932/b41cc588-c189-11e4-99ce-d032eac9b602.png)

**Comment by diplomod** [comment]
I see. But th picture you've set is not displayed here:
![screen shot 2015-03-03 at 15 16 20](https://cloud.githubusercontent.com/assets/7487883/6464123/4e8bbe48-c1b8-11e4-9bb8-9937ff9f83a4.png)
Can we show there the picture that is set as "featured image"?

**Comment by bokiftw** [comment]
Oops, sorry. This works now.
