### ISSUE TITLE
Geology: Subheadline mandatory but is not shown

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#52]
![screen shot 2015-02-17 at 21 06 06](https://cloud.githubusercontent.com/assets/7487883/6236226/e53df0ac-b6e8-11e4-824c-ac53ffbb6170.png)
![screen shot 2015-02-17 at 21 06 15](https://cloud.githubusercontent.com/assets/7487883/6236229/ea7aef8e-b6e8-11e4-9980-673105f2753a.png)
For what do we need the subheadline?

**Comment by bokiftw** [comment]
This field is not needed anymore, since now that sub headline changes with the image. It was used before we changed that it is being change with the image. I deleted this field.

**Comment by diplomod** [comment]
Excellent, more clear this way. Thanks.
