### ISSUE TITLE
Edit news and community

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#54]
How can I edit these?

![screen shot 2015-02-17 at 21 26 22](https://cloud.githubusercontent.com/assets/7487883/6236553/c029a7fe-b6eb-11e4-9493-2e9ccbf4d022.png)

![screen shot 2015-02-17 at 21 26 31](https://cloud.githubusercontent.com/assets/7487883/6236563/c9fefb76-b6eb-11e4-8fa4-210a48f5b98e.png)

**Comment by bokiftw** [comment]
I thought this will be generated dynamically so I just made a static elements and styled it. So now, it needs to be changed from the code. I didn't know how you wanted it to display?

**Comment by diplomod** [comment]
The community will be sourced by the interface with geonova.no
@Immoz Correct? :)

The news I thought we edit in nordryggen.no and then link to geo365.no. But actually I could check if we can create an interface here so that news on geo365.no in the category "nordryggen" (http://www.geo365.no/nordryggen/) are displayed automatically.
I'll check and let you know.

**Comment by diplomod** [comment]
we decided to create a new post type on dokuhl quickly
