### ISSUE TITLE
Submit: Disclaimer

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#55]
We shall add a disclaimer in the submit page at the end.

A simple mandatory checkbox that says "I agree that this information can be used in NGU’s database for geodiversity."

![screen shot 2015-02-17 at 21 46 13](https://cloud.githubusercontent.com/assets/7487883/6236859/70ca539a-b6ee-11e4-8ccc-2cefec4a9250.png)

**Comment by bokiftw** [comment]
This is done.

**Comment by diplomod** [comment]
yes, thanks

**Comment by bokiftw** [comment]
If this is going to be translated, please send me the translations.

**Comment by diplomod** [comment]
Norwegian: 
Jeg godtar at denne informasjonen kan brukes i NGU’s database om geodiversitet

German:
Ich stimme zu, dass die von mir eingereichten Informationen für die Datenbank für Geodiversität von NGU genutzt werden können.

**Comment by bokiftw** [comment]
Did this.

**Comment by diplomod** [comment]
OK - but the problem is I don't get to the Norwegian and German submission pages any more. Please see #48 & #94
