### ISSUE TITLE
Mountain Regions & Geology: Thumbnails below selcted region don't link

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#56]
When I have opened a mountain region or a geological category, the thumbnails below it don't work to open other mountain regions/geological category:
![screen shot 2015-02-18 at 17 53 03](https://cloud.githubusercontent.com/assets/7487883/6251965/3d48cfe8-b797-11e4-8ef0-949a57a17e49.png)

**Comment by bokiftw** [comment]
Now, you firstly need to close opened Mountain region and then click another to open. Do you want to work differently and how?

**Comment by diplomod** [comment]
of course - I want to click on it and the one that I clicked on opens.

Regardless whether another montain region is opened or not. It is absolutely not intuitive that I need to close the opened one first.

**Comment by bokiftw** [comment]
This is done. It opens another mountain without closing another first.

**Comment by diplomod** [comment]
Excellent, thanks
