### ISSUE TITLE
Geofunn view

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#57]
Where is it?
I have created a few geofunn, but I can't find the detailed view any more:
![04_nordyggen_geofun_wordpress_comments](https://cloud.githubusercontent.com/assets/7487883/6268816/ac54b024-b84f-11e4-9b14-7a215253f41f.jpg)

**Comment by diplomod** [comment]
see also #19

**Comment by bokiftw** [comment]
I don't see where you made it? 

You need to make a new page, and as **template** set the **geofunn**.

For example I made new geofunn page for EN language, and here it is: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/en/geofunn-new/

**Comment by diplomod** [comment]
we created a new post type for goefunn
