### ISSUE TITLE
Translation: Always include new fields also for copy of content

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#58]
When I try to create a translation and copy the content from one language, new custom fields are not copied:

![screen shot 2015-02-24 at 22 40 14](https://cloud.githubusercontent.com/assets/7487883/6359873/51bf892e-bc76-11e4-85be-291dff45caff.png)

**Comment by bokiftw** [comment]
I could reproduce this error by myself, but if I understood you correctly, I suggest you to translate these pages with custom fields by duplicating them.

So on the right side you will see this:
![screen shot 2015-03-01 at 23 08 53](https://cloud.githubusercontent.com/assets/5833593/6433186/8034e4fc-c068-11e4-9af4-7d8ae164d2e6.png)

Check duplicate and after you will be able to edit content and also all custom fields and galleries will be copied.

**Comment by diplomod** [comment]
OK, we'll try that
