### ISSUE TITLE
Replace Lundin logo

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#60]
Please replace the Lundin logo in the footer with this image:

![532x220 nordryggen_sponsor bottom](https://cloud.githubusercontent.com/assets/7487883/6361524/73539654-bc83-11e4-9862-3fccd18dace6.jpg)

**Comment by bokiftw** [comment]
Done.

**Comment by diplomod** [comment]
Thanks. Where can I do it?

**Comment by bokiftw** [comment]
![screen shot 2015-02-25 at 12 32 28](https://cloud.githubusercontent.com/assets/5833593/6369870/9ba8047a-bcea-11e4-826c-7ea924bd41b0.png)

It is done inside the code. In the **footer.php** file, like in the image above. So when you upload sponsor image into the folder images, go to footer.php and change the name of the image, which is underlined in red.

**Comment by diplomod** [comment]
@Immoz Bitte das gleiche auf dokuhl machen - danke

**Comment by Immoz** [comment]
done!?

**Comment by diplomod** [comment]
Nein - ist ja nach wie vor sichtbar. Kannst du das schnell machen? Code-Stelle ist ja oben angegeben.

**Comment by Immoz** [comment]
ich kann das problem grad nicht nachvollziehen. das bild was du oben gepostet hast wird doch links richtig angezeigt?

Dokuhl:
![2015-04-01 10_28_44-nordryggstien no _ explore the nordryggstien](https://cloud.githubusercontent.com/assets/1924026/6937200/05940fc0-d85a-11e4-8e57-b3618cdb6a83.png)

**Comment by diplomod** [comment]
Richtig.

Aber oben Rechts ist das Logo noch sichtbar:
![screen shot 2015-04-01 at 11 12 10](https://cloud.githubusercontent.com/assets/7487883/6937970/03b97a7c-d860-11e4-979f-fbdd807eac80.png)

**Comment by Immoz** [comment]
Aah ok, weil oben die rede vom footer war. Ich habs angepasst - das ist im Adminbereich "Appearance->Header" einstellbar.

**Comment by diplomod** [comment]
merci :)
