### ISSUE TITLE
Geofunn: Thumbnail Slider pictures not mandatory

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#63]
![screen shot 2015-02-25 at 00 33 34](https://cloud.githubusercontent.com/assets/7487883/6361765/ffae4f48-bc85-11e4-8df4-51ec9280eb54.png)

**Comment by bokiftw** [comment]
OK, I set it not required, but I will leave that in case of images at least 2 of them must be filled in. It will preserve from errors when slider has only one element. So let's have in mind that slider which are going in loop must have at least 2 items. Backend guys should informed of this.

**Comment by diplomod** [comment]
OK - thanks.
@Immoz FYI
