### ISSUE TITLE
Can we change the pictures here?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#65]
![screen shot 2015-02-25 at 12 35 44](https://cloud.githubusercontent.com/assets/7487883/6369892/dce99d90-bcea-11e4-910c-fefe94212f08.png)

I need to have here more faces for a presentation this afternoon... 
Can w take them from here?
http://www.geonova.no/members/

![screen shot 2015-02-25 at 12 37 03](https://cloud.githubusercontent.com/assets/7487883/6369910/0dcda528-bceb-11e4-9393-f1bcdb807235.png)

**Comment by bokiftw** [comment]
I must be logged in to see this page. In that case can you please, take some 6 pictures and give me the links to that pictures? 

So I will just link images not crop and upload, etc..

**Comment by diplomod** [comment]
we'll solve by liniking to the community anyway
