### ISSUE TITLE
Trail

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#66]
http://ut.no/tur/2.6217/
@Immoz 
@philipdomann 

Arbeiten wir mit dem erst mal. Geht das?

**Comment by philipdomann** [comment]
was soll denn noch kommen?

**Comment by diplomod** [comment]
ein update - der ist nicht komplett (im Süden geht noch was ab). Aber ich verstehe von deine Antwort, dass es grundsätzlich geht mit so einer Datei?

**Comment by philipdomann** [comment]
Ok, wir wissen beide nicht genau um was dabei geht.
Was soll mit dieser Webseite/Datei?

**Comment by diplomod** [comment]
Ich dachte wenn ihr die Map einbindet und den Trail darstellen sollt, dann könnt ihr derweil mal die Datei nehmen. Der rail wird noch weiter überarbeitet, aber für Teten und so wäre das schon mal ein guter Anfang.

**Comment by Immoz** [comment]
Ich hab den Trail jetzt mithilfe der Datei eingebunden. Man kann dann prinzipiell einfach die Datei auf dem Server austauschen, falls der Trail mal geupdated wird.

**Comment by diplomod** [comment]
sehr gut. Bin noch etas unschlüssig, wie das funktioniert - die ANzeige ist irgendwie strange. Aber können wir uns ja morgen in Ruhe anschauen.
