### ISSUE TITLE
Trail-Alternative in extra Farbe

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#69]
Ich gehe davon aus, dass man weitere Trail-Alternativen (z.B. Seitenarme) easy integrieren kann. Können diese dann auch eine andere Farbe haben? 
Du brauchts eine gpx-Datei, oder?

**Comment by Immoz** [comment]
Jo, das lässt sich integrieren - auch mit unterschiedlichen Farben. GPX-Dateien machen sich dazu ganz gut.

**Comment by diplomod** [comment]
Ich muss hier nochmal nachhaken wegen den fehlednen Trail-Stücken. Dann gehen wir das Tehma nochmal an.

**Comment by philipdomann** [comment]
d.h. es soll einer bzw. weitere Trails noch eingebunden werden?

**Comment by diplomod** [comment]
Nein - wir werden einen noch exakteren Trail liefern bzw. die fehlenden Stücke, welche Tom jetzt erst mal via Luftlinie verbunden hat, mit exakten gpx Dateien ersetzen.
