### ISSUE TITLE
Extra page like Geologi and Fjellheimer

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#70]
Can we have an extra page for these contents in the exact same layout like "Fjellheimer" and "Geologi"?

This: http://dokuhl.de/nordryggen/nb/about/geologisk-attraksjoner/

Like this: http://dokuhl.de/nordryggen/nb/geologi/

**Comment by bokiftw** [comment]
For this I will need to add new template page and new post types which will stay in sidebar (like Geology and Mountain regions). Just tell me how would you like this page template to be called and also the name of the posts type in the sidebar? All input fields are exactly the same like in Geology/Fjellheimer?

**Comment by diplomod** [comment]
Call it "Attractions"
All the same :)
Thanks A!

**Comment by bokiftw** [comment]
I also implemented this, you can check it here: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/en/attractions/

I just put it only for EN version. I will contact backend guy how we will exchange these updates on database.

**Comment by diplomod** [comment]
Perfect, thanks.
@Immoz Borjan will get i touch with you regarding the update

**Comment by diplomod** [comment]
seems to work, thanks
