### ISSUE TITLE
Move down links in Geologi/Fjellheimer page

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#71]
Can you place the links not with the pictures on top but next to the text (where we have recently added the WYSIWYG editor)? Kind of like this:

![screen shot 2015-03-12 at 17 39 43](https://cloud.githubusercontent.com/assets/7487883/6622779/124da6e8-c8df-11e4-849b-2a2131625839.png)

**Comment by bokiftw** [comment]
In this case, these links need to static, they can't be changed with different image. So I would made them stay there fixed, and constantly the same link. Otherwise, I can't make it, because changing elements should stay in same parent element.

**Comment by diplomod** [comment]
That's fine!

**Comment by bokiftw** [comment]
I have changed this. You can take a look to see if you like it, but that's the way I managed to do it. Hope it is alright.

**Comment by diplomod** [comment]
Looks fine, thanks. 
(I will close this issue when it is transferred to dokuhl.de/nordryggen successfully)

**Comment by diplomod** [comment]
OK, great.

Can you change the wording in the link "NORDRYGGEN NYHETER" to only "NYHETER"?

@Immoz The link "SE EXEMPLER" should go to the map where this geological category is activated as a filter for the geofunn. Can you do that?

**Comment by Immoz** [comment]
@lukassiedel will take care about this in the next few days

**Comment by diplomod** [comment]
works, fine
