### ISSUE TITLE
Change Option 1 & 2 in Login

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#72]
Can you change the login dialogue - 

Option 1 should be "Enter your email address and name"

Option 2 should be "Use your geonova account and engage in the geoscience community"

@Immoz Does it interfere with your changes for the captcha etc. if this is changed by Borjan?

**Comment by bokiftw** [comment]
Done. Will contact backend guys how to send them all these changes.

**Comment by diplomod** [comment]
Thanks

**Comment by diplomod** [comment]
We have some confusion here now. Please correct:

This should be under Option 1:
![screen shot 2015-04-01 at 22 12 34](https://cloud.githubusercontent.com/assets/7487883/6951558/7ce98660-d8bc-11e4-8419-257ff288afd7.png)

This should be under Option 2:
![screen shot 2015-04-01 at 22 12 48](https://cloud.githubusercontent.com/assets/7487883/6951566/8a8fa25e-d8bc-11e4-9d7c-ab7cd2054718.png)

Currently, this is switched:
![screen shot 2015-04-01 at 22 13 00](https://cloud.githubusercontent.com/assets/7487883/6951574/97ee47e8-d8bc-11e4-9a16-562699a8c78f.png)

**Comment by bokiftw** [comment]
okay, it was confusion. Now it is fixed and merged to dokuhl.

**Comment by diplomod** [comment]
Now it's totally confused:

![screen shot 2015-04-09 at 22 43 43](https://cloud.githubusercontent.com/assets/7487883/7076488/16cf5b3a-df0a-11e4-853f-b2b05bb14fbd.png)

**Comment by bokiftw** [comment]
Sorry I didnt see other pages, I just updated page in English language.

So I guess now all are fine: 
http://dokuhl.de/nordryggen/login/

**Comment by diplomod** [comment]
Now we got it - thanks
