### ISSUE TITLE
Kategorien

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#73]
- Geologische => Checkboxes
- Geografisch Berge => Dropdown
- Geografisch Land (Fylke) => Dropdown
- Qualitative => Checkboxes
- Achtung: gofunn können in der Kategorie Geologie und Qualitative durchaus auch Mehrfachnennungen haben

**Comment by diplomod** [comment]
Können wir die in der Submission-Page auch anlegen jetzt?

**Comment by Immoz** [comment]
Das geht im Admin-Bereich unter dem Punkt "Geofunn". Dort kannst du sämmtliche Kategorien (Geology, Fjellheimer, Quality, County/Fylke) hinzufügen/anpassen.

![2015-03-30 13_06_54-geologies nordryggstien no wordpress](https://cloud.githubusercontent.com/assets/1924026/6895208/f81cb52c-d6dd-11e4-9555-2d9b7fae8439.png)

**Comment by diplomod** [comment]
cool - mach ma, merci

**Comment by diplomod** [comment]
perfekt, merci.
Name wird angezeigt, wenn via email bzw. mit Bild wenn via Geonova eingerecit wird, korrekt?

**Comment by Immoz** [comment]
Bin mir nicht sicher, ob ich die frage richtig verstanden habe. Also die kategorien die ihr im adminbereich festlegt, sollten genauso beim einreichprozess angezeigt werden.

**Comment by diplomod** [comment]
Jaja - ich meinte, ob der Name eines Users angezeigt wird, wenn man in de Zukunft einen Geofunn einreicht - etweder durch eingabe beim Login in Option 1 (Name und Email-Adresse + Captcha) oder eben Geonova account.

BTW: #103

**Comment by Immoz** [comment]
Jo das sollte angezeigt werden.
