### ISSUE TITLE
Anpassungen Map

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#75]
- Ausblenden der roten Trails (Aktuell “Nordrygnensean” => Umbennen in “Trails")
- Unbedingt Trail und Geologi vorausgewählt
- “Geologi” in “Geofunn” umbennen
- Trail in “Nordryggstien” umbenennen
- Hytten nur entlang des Trails anzeigen (wie viele km entfernt hängt ein bisschen davon ab, wie genau das gesteuert werden kann)
- Hytter sollten den Link zur Seite auf ut.no öffnen => Müsste von DNT kommen (klärt Hans ab bzw. Tom schaut nochmal ob nasjonalturbase URLs ausliefert)
- Preview der geofunn auf der map: Anzeige “Fjellheim”, “Fylke” (z.B. “Rondane, Sør-Trøndelag”)
- “NORDRYGGENSTEIN” => “NORDRYGGSTIEN”
- Zoom mit Mouse erst wenn ich die Map einmal angeklickt habe. (Text drunter “Click map once to activate auto zoom by mouse wheel scrolling”)

**Comment by diplomod** [comment]
Folgende Punkte noch:
- Überschrift der Map: "NORDRYGGSTIEN" (immer noch "NORDRYGGENSTIEN" - ein EN muss raus)
- Default Menü ausgeklappt (Pfeil dann umkehren, siehe #88 )
- Hytter: Siehe #89 
- Hytter: Ich kann keine Links öffnen, es wird nur der Name angezeigt. Diese müssen auf ut.no verlinken (z.B. http://ut.no/hytte/3.2207/)
- "ANDRE GEOFUNN" (ein E zu viel)
- Die fhellheimer sollten ein Dropdown sein (Mehrfachauswahl macht ja keinen Sinn, ich kann ja nicht mhrere gelichzeitig anzeigen). Außerdem ist die Liste nicht komplett.
- Ausrichtung der Preview nicht optimal: Der Rand wird häufig abgeschnitten:
  ![screen shot 2015-03-30 at 09 14 56](https://cloud.githubusercontent.com/assets/7487883/6891641/649f5e6e-d6bd-11e4-999e-b68b0d47788e.png)
- Aktivieren der Map auch problematisch: Siehe #85 
- Menü sollte sich idealerweise dem Bildschirm anpassen und nicht scrollbar sein (sollte mit dem Dropdown für Fjellheimer erledigt sein):
  ![screen shot 2015-03-30 at 09 00 50](https://cloud.githubusercontent.com/assets/7487883/6891934/33950628-d6bf-11e4-86c7-e02feeba6f56.png)
- Suche default ausgeklappt anzeigen - check kein Mensch, dass sich da eine Suche dahinter verbirgt:
  ![screen shot 2015-03-30 at 09 31 18](https://cloud.githubusercontent.com/assets/7487883/6891965/99db555e-d6bf-11e4-9962-80023b8eabfe.png)
- Wenn möglich: Suchergebnisse default etwas weiter herusgezoomt anzeigen (man kennt sich nicht aus, wenn man voll auf die Map reinzoomt - meist wird auf dem niedrigsten Level eh nichts direkt angezeigt, was einem bei der Orientierung hilft)

**Comment by Immoz** [comment]
Die beiden issues sollten besser vom anderen team gefixt werden:
- Default Menü ausgeklappt (Pfeil dann umkehren, siehe #88 )
- Suche default ausgeklappt anzeigen - check kein Mensch, dass sich da eine Suche dahinter

**Comment by diplomod** [comment]
OK - an den anderen Punkten bist du dran?

**Comment by Immoz** [comment]
jo den rest kann ich machen

**Comment by diplomod** [comment]
Notiz: Fjellheimer im Menü der Map erst mal komplett ausblenden

**Comment by philipdomann** [comment]
Zusammenfassung:
bereits done: \* Fjellheimer im Menü der Map erst mal komplett ausblenden
- Wenn möglich: Suchergebnisse default etwas weiter herusgezoomt anzeigen (man kennt sich nicht aus, wenn man voll auf die Map reinzoomt - meist wird auf dem niedrigsten Level eh nichts direkt angezeigt, was einem bei der Orientierung hilft)
- Menü sollte sich idealerweise dem Bildschirm anpassen und nicht scrollbar sein (sollte mit dem Dropdown für Fjellheimer erledigt sein)
- Aktivieren der Map auch problematisch: Siehe #85
- Ausrichtung der Preview nicht optimal: Der Rand wird häufig abgeschnitten
- Hytter: Siehe #89
- Hytter: Ich kann keine Links öffnen, es wird nur der Name angezeigt. Diese müssen auf ut.no verlinken (z.B. http://ut.no/hytte/3.2207/)
- "ANDRE GEOFUNN" (ein E zu viel)
- Überschrift der Map: "NORDRYGGSTIEN" (immer noch "NORDRYGGENSTIEN" - ein EN muss raus)

**Comment by diplomod** [comment]
Korekt. Wobei der erste Punkt schon erledigt ist.

**Comment by lukassiedel** [comment]
Welche der Punkte sind jetzt noch offen? Die Typos scheinen behoben zu sein. Die Links der Hytter scheinen auch zu gehen. 
"Ausrichtung Preview nicht optimal": welche Preview ist da gemeint?
ich überseh sicher was^^

**Comment by diplomod** [comment]
Aktuell wüsste ich auch keine Baustellen zu dem Thema mehr, schaut derweil gut aus. ich schrei, wenn mir doch noch was einfällt. :) Danke.
