### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#78]
- Gewünscht: Anzeige der Userbilder von Geonova-Members, die geofunn beigetragen haben (bzw. sich einmal einglogged haben)
- Ggf. ausblenden, wenn nicht genug verschiedene Leute
- "See all” einfach auf geonova.no/members verlinken

**Comment by Immoz** [comment]
soweit umgesetzt außer: "Ggf. ausblenden, wenn nicht genug verschiedene Leute"

Wenn du dazu eine konkrete Regel hast bzw. eine Option im Adminbereich wünschst - einfach nochmal aufmachen bitte.

**Comment by diplomod** [comment]
Ich hätte das tatsächlich gerne als Option im Admin-Bereich. Für den Anfang werden wir das ausblenden müssen, weil die ersten Wochen und Monate die Geonova-User sicht nicht so oft einloggen werden, damit das interessant wird. Es würden immer die gleichen angezeigt werden.

Alternative: Wir nehmen einfach die Geonova User-Bilder (wenn möglich nur User-ID, keine Klarnamen in den Bildern wegen Google) und lassen die lustig da drauf rotiere - erstmal ohne connection zur Submission von geofunn.
Machbar?

**Comment by Immoz** [comment]
Ok ich habe jetzt unter "Appearance->Nordryggen-options" entsprechende einstellmöglichkeiten eingebaut und die geschichte mit geonova verbunden.
![Uploading 2015-04-01 14_52_41-Nordryggen-Options ‹ nordryggstien.no — WordPress.png . . .]()

**Comment by Immoz** [comment]
Ok upload geht gerade nicht, aber sollte zu finden sein :)

**Comment by diplomod** [comment]
Super.

Hab das jetzt mal so eingestellt, aber es werden noch keine Geonova members gezeigt. Dauert noch bis das läuft? Cache hatte ich geleert.

![screen shot 2015-04-01 at 15 12 55](https://cloud.githubusercontent.com/assets/7487883/6941643/d65cfdfc-d881-11e4-811e-6649212f4991.png)

**Comment by Immoz** [comment]
ja ist etwas ungünstig zum testen denn momentan holt er die ja von dokuhl/geonova .. da sind glaub ich die gleichen drauf, die auch bei nordryggen angemeldet sind.
