### ISSUE TITLE
Missing the red arrow

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#8]
![screen shot 2015-01-23 at 17 43 41](https://cloud.githubusercontent.com/assets/7487883/5878474/6f2a2e64-a327-11e4-8936-c01e779b31e7.png)
vs.
![screen shot 2015-01-23 at 17 43 50](https://cloud.githubusercontent.com/assets/7487883/5878479/75390c76-a327-11e4-92b5-ccdb14d176b9.png)

**Comment by bokiftw** [comment]
Red arrow is added to the site.

**Comment by diplomod** [comment]
Yes, thanks. Now it also needs to have a function. :) When you click on it, the page should scroll down to the map.

**Comment by bokiftw** [comment]
This is done, feel free to test it.
