### ISSUE TITLE
Change in Branding

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#80]
We decided to change the name of the page from nordryggen.no to nordryggstien.no

Only valid now:
- nordryggstien.no
- Nordryggstien
- #nordryggstien

This affects:

Logo:
![screen shot 2015-03-23 at 20 25 47](https://cloud.githubusercontent.com/assets/7487883/6788582/df5105cc-d19a-11e4-8397-a1678064fdcb.png)
=> @Igor: Can you provide a new logo with "NORDRYGGSTIEN"?

News section
![screen shot 2015-03-23 at 20 30 38](https://cloud.githubusercontent.com/assets/7487883/6788688/8ebe4eac-d19b-11e4-8b72-feb664e84c3c.png)
@Borjan: please change to "NORDRYGGSTIEN NYHETER" (Norwegian), "NORDRYGGEN TRAIL NEWS" (English) and "NORDRYGGEN TRAIL NEWS" (German)

Instagram section
@bokiftw Please change from "#NORDRYGGEN" to "#NORDRYGGSTIEN"

The rest I believe can be edited in the admin section.

**Comment by bokiftw** [comment]
Done. I guess that's everything that must be done inside code translation.

**Comment by diplomod** [comment]
Thanks.

The logo is too tiny - wrong scale I guess:
![screen shot 2015-03-30 at 10 00 07](https://cloud.githubusercontent.com/assets/7487883/6892353/9467653c-d6c3-11e4-87cd-13bf032bdc63.png)

**Comment by bokiftw** [comment]
Fixed. See here: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/

**Comment by diplomod** [comment]
Much better! Make sure it's transferred to the dokuhl.de/nordryggen system, please.
Thanks

**Comment by diplomod** [comment]
Looks good. Just one detai I found: This button on the home screen should say "UTFORSKE NORDRYGGSTIEN" (not "NORDRYGGSTEIN")
