### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#81]
How do I set the links here?

![screen shot 2015-03-23 at 20 51 58](https://cloud.githubusercontent.com/assets/7487883/6789143/77b9d804-d19e-11e4-8be2-c9f8dbbd1b99.png)

**Comment by bokiftw** [comment]
Well this is also changed inside the code.

if it's a top bar socials it is changed inside header.php in these lines:
![screen shot 2015-03-24 at 23 58 50](https://cloud.githubusercontent.com/assets/5833593/6814757/d5174fc0-d281-11e4-8902-dc611f8c3766.png)

Or if it is inside footer, in footer.php in these lines:
![screen shot 2015-03-24 at 23 57 08](https://cloud.githubusercontent.com/assets/5833593/6814762/e60ed9e2-d281-11e4-9833-8545830dc120.png)

You can send me which link you want where and I will put it.

**Comment by diplomod** [comment]
OK - please set these links for now:

Twitter: https://twitter.com/Geo365
Facebook: https://www.facebook.com/GeoPublishing
Instagram: https://instagram.com/utno/
(You need to replace the Pinterest-logo with instagram)

We will need to change it again soon, but I believe it's not a big deal. Correct?

**Comment by bokiftw** [comment]
Done this. Made it to open in new tab. Yes, it pretty easy to accomplish that. just another icon path :)

**Comment by diplomod** [comment]
Thanks -the icon does not really fit:
![screen shot 2015-03-30 at 08 45 34](https://cloud.githubusercontent.com/assets/7487883/6891285/5ceefdd6-d6b9-11e4-9c16-3468a72ac1e0.png)
Can Igor check please?

**Comment by bokiftw** [comment]
Check this out here: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/
Is it okay?

**Comment by diplomod** [comment]
excactly, thanks!
