### ISSUE TITLE
Formatting of comments on normal pages

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#83]
When I create a normal new page, the comments lack formatting:

![screen shot 2015-03-24 at 21 02 02](https://cloud.githubusercontent.com/assets/7487883/6811569/1c41c3a8-d269-11e4-9dc6-769b19907d51.png)

**Comment by bokiftw** [comment]
I think I fixed this, since I don't know exactly which page and how you have created. Now when you create a page without seeing a template, this things ( un-styled sidebar) will not show.

**Comment by diplomod** [comment]
Sorry, I forgot the link: dokuhl.de/nordryggen/nb/halfdan-pa-nordryggstien
See the search below the comment.

Looks good on http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/test-blog/
However, please make sure it is transferred succssfully to dokuhl.de/nordryggen

**Comment by diplomod** [comment]
looks good, thanks
