### ISSUE TITLE
Picture-Upload schließt nie ab

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#84]
Ich kann zwar Bilder hochladen, aber der Dialog wird nie geschlossen, der Upload-Fortschritt-Balken bleibt irgendwo hängen.
Wenn ich das ganze dann schließe , ist das Bild aber da.

![screen shot 2015-03-29 at 15 22 01](https://cloud.githubusercontent.com/assets/7487883/6885604/a59f4af0-d627-11e4-9889-5409a24bbf80.png)

**Comment by Immoz** [comment]
Hatte sich ja erledigt oder? Da ich auch ab und zu das problem habe, dass der adminbereich ca 1 mal pro tag etwa 2 minuten braucht um vollständig zu laden, sollten wir das etwas beobachten. Allerdings konnte ich den Fehler bisher nicht bei mir lokal feststellen sondern nur auf dokuhl. Ich glaube, dass ich das problem auf die sprachplugins zurückverfolgen konnte, die wahrscheinlich ab und zu irgendein skript durchlaufen lassen, welches ne weile braucht um sämmtliche dateien nach neuen Texten durchsucht, die übersetzt werden können. Schaun wir mal ...

**Comment by diplomod** [comment]
alles klar - passt, merci
