### ISSUE TITLE
Map: Wir brauchen eine Möglichkeit, wieder rauszugehen

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#85]
Das aktivieren via click ist schön, aber danach komme ich nie wieder von der Map weg.

Es braucht so einen roten Pfeil nach oben und unten - immer.

Kannst du den einbauen?

**Comment by diplomod** [comment]
Hab jetzt einen Pfeil entdeckt, aber der steckt mitten in der Map:
![screen shot 2015-03-30 at 09 00 25](https://cloud.githubusercontent.com/assets/7487883/6891451/82c721da-d6bb-11e4-8d23-0e153b4df311.png)

**Comment by Immoz** [comment]
der pfeil aus deinem screenshot ist der der zum slider gehört und wird momentan von den anderen gefixt. ich habe jetzt noch entsprechende buttons für die map hinzugefügt um aus dem bereich wieder raus zu kommen.

**Comment by diplomod** [comment]
Ja, aber der ist etwas wild mitten drin platziert:
![screen shot 2015-03-31 at 09 36 36](https://cloud.githubusercontent.com/assets/7487883/6914343/aa041c0c-d789-11e4-9b30-fe924e0273cd.png)

**Comment by Immoz** [comment]
Kannst du nochmal cache leeren?

**Comment by Immoz** [comment]
Ich habs nochmal mit meinen browsern gecheckt und scheint überall zu funktionieren. Ich mach der übersicht halber nochmal zu. Kannst ja wieder öffnen wenns doch noch irgendwo bei dir hakt.

**Comment by diplomod** [comment]
ok - schaut gut aus
