### ISSUE TITLE
Norwegisch default

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#86]
ich hätte gerne, dass wenn man dokuhl.de/nordryggen bzw. in Kürze dokuhl.de/nordryggstien bzw. sobald wir live sind nordryggstien.no aufruft, die Norwegische version als default kommt und nicht die Englische.
Kannst du das einstellen oder muss das Martin machen?

**Comment by Immoz** [comment]
Müssen wir nochmal untereinander abklären, da wir das theoretisch beide machen können. Ist in jedem Fall aber nur eine winzige Anpassung nötig.

**Comment by lukassiedel** [comment]
der Tom meint er hätte das schon bezüglich eines anderen Issues gemacht?!

**Comment by diplomod** [comment]
Ja, das passt jezt grundsätzlich. Betrachten wir das mal als erledigt für's erste. Danke!
