### ISSUE TITLE
geofunn in Norwegischer Version

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#87]
Die importierten geofunn müssten schon in der Norwegischen (und Deutschen) Version sichtbar sein - aktuell sind die nur in der Englischen Version sichtbar.
Übersetzung ist jetzt mal egal. Nur leer darf es nicht sein:
![screen shot 2015-03-30 at 08 53 04](https://cloud.githubusercontent.com/assets/7487883/6891338/325fb58c-d6ba-11e4-8218-152d4280ac05.png)

**Comment by diplomod** [comment]
Kann man das der Form halber (und für etwaige bersetzung in der Zukunft) auch so einstellen, dass de Geofunn im Adminbereich als Sprache Norwegisch erfasst sind?

![screen shot 2015-03-30 at 09 38 00](https://cloud.githubusercontent.com/assets/7487883/6892050/9c7d4226-d6c0-11e4-8801-9a9880e21563.png)

**Comment by Immoz** [comment]
sollten jetzt in allen 3 sprachen dargestellt werden

**Comment by diplomod** [comment]
Ja, das scheint zu laufen. 

ABer dafür habe ich jetzt wieder das falsche Symbol...
![Uploading Screen Shot 2015-04-01 at 22.06.12.png . . .]()

**Comment by Immoz** [comment]
Kannst den screenshot bitte nochmal uploaden? Weiß gerade nicht genau welches du meinst.

**Comment by diplomod** [comment]
![screen shot 2015-04-02 at 16 56 21](https://cloud.githubusercontent.com/assets/7487883/6966424/373459f4-d959-11e4-9a2a-29712c3affe2.png)
