### ISSUE TITLE
Pfeil zum ausklappen des Menü der Map umkehren

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#88]
Der Pfeil muss in beide Richtungen gehen: Eingeklappt nach rechts, ausgeklappt nach links.
Außerdem sollte der nicht den Zoom überdecken.
![screen shot 2015-03-30 at 08 55 01](https://cloud.githubusercontent.com/assets/7487883/6891400/0b8de41e-d6bb-11e4-8b2c-e67a7624bb6a.png)

**Comment by Immoz** [comment]
Das sollte wahrscheinlich das andere team anpassen.

**Comment by diplomod** [comment]
@bokiftw Can you edit the arrow that is on the top of the menu in the map (see picture above)? It should change direction when the menu is opened: Then the arrow should guide to the left (indicating that you can close the menu again), not to the right.

**Comment by diplomod** [comment]
Now that the menu is default opened, can you pls change the direction of the arrow so that is directs to the left usually (menu opened)?
It should direct to the right only when the menu is closed.

![screen shot 2015-04-10 at 15 02 26](https://cloud.githubusercontent.com/assets/7487883/7088279/c1299130-df92-11e4-9696-810dcdd86776.png)

**Comment by bokiftw** [comment]
Okay, this is done. Will update files.

**Comment by diplomod** [comment]
Very good.
Please make sure it's in the next update

**Comment by diplomod** [comment]
Finally!
But: I liked the design before better - now it has two arrows, one looks better. Please change back if possible:
![screen shot 2015-04-30 at 17 07 41](https://cloud.githubusercontent.com/assets/7487883/7415817/7dbeeff2-ef5b-11e4-9f01-b59f48e49809.png)

**Comment by bokiftw** [comment]
Okay, I just make this like in design, since that one icon left from test phase. I can make it just like one white arrow, but would you like this red space to be square or like before?

**Comment by diplomod** [comment]
Thanks, Just as before (not square but hgher than broad). Like Igor has designed it.

**Comment by bokiftw** [comment]
Done.

**Comment by diplomod** [comment]
:)
