### ISSUE TITLE
Hytter in Map

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#89]
Ich stelle fest, dass die Hytter wie besprochen entlang des Nordryggstien gefiltert sind (hat zumindest den Anschein).

Wir haben jetzt noch genauere Daten: Wir könnten exakt die Hytter, welche direkt auf dem Nordryggstien liegen, default mit anzeigen.

Alle anderen (inklusive jener Hytter fern ab des Trails) mit einem extra Menüpunkt (checkbox, nicht default) unter "ANDRE HYTTER" ins Menü aufnehmen.

Machbar? Wenn ja würde ich dir die Hytter-links (inkl. ID) schicken. (z.B. http://ut.no/hytte/3.2207/)

**Comment by Immoz** [comment]
Jo, das können wir so machen.

**Comment by diplomod** [comment]
top
