### ISSUE TITLE
Where do I change the menu?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#9]
Don't find it
![screen shot 2015-01-23 at 17 44 53](https://cloud.githubusercontent.com/assets/7487883/5878496/993911d4-a327-11e4-9b07-093a8613289b.png)
If the demo user does not have the according rights, please make me super mega admin - I need all the rights, otherwise I am half blind and will continue asking stupid questions. :)

**Comment by bokiftw** [comment]
Now demo user have administrator permissions, so you can edit menu in the Appearance > Menus. There you have full control of the implemented menu. Please, notice just one thing. Do not make new or change page names depends on language. For example, pages that we made in english should stay the same name attached to the English language, but if you want to change page's display name in the menu, you will do it by changing the Navigation Label option, while original should stay. Menu can also be translated with this plugin, so no need to make new pages just for menu.

eg: Navigation label: Welcome to Nordryggen Tail Original: About

![nav](https://cloud.githubusercontent.com/assets/5833593/5892779/64727814-a4cb-11e4-8a6d-66d2f5f2b082.png)

**Comment by diplomod** [comment]
OK - in principal it works. But I do have trouble with the translations. Should they work?

Regarding the original page titles: Since you are giving the pages freestyle titles, I will want to change them. So either  I get a possibility to re-name the original pages or we can go through the pages before hand and agree on the titles.

**Comment by bokiftw** [comment]
Yes, translation should work fine. If I understood you correctly, yes you can change page title, even if I put page names on my own. But, what you should take care is that current pages stay default pages and for default language (English). So not to make new page for english called 'welcome to nordryggen' and this actual page called 'about' to put it to Norwegian language and just rename it. This will effect the hyperlink, which you can see under the page title.
So, arrangement of pages and links should look like: 
wordpress/about - English
wordpress/no/about  - Norwegian
wordpress/de/about - German
but titles can be however you like.

Anyways, would you like to give me the names of page titles in all languages, so I can do it for you? Also, you should give me the pages you want in the navigation and I will put it.

**Comment by diplomod** [comment]
OK - here we go:

EN (default):
-> ABOUT NORDRYGGEN
---> WELCOME TO THE NORDRYGGEN GEOTRAIL
---> NORDRYGGEN GEOLOGY
---> MOUNTAIN REGIONS OF NORWAY
-> EXPLORE NORDRYGGEN GEOTRAIL
-> CONTRIBUTE GEOFUNN

NO:
-> OM NORDRYGGEN
---> VELKOMMEN TIL NORDRYGGSTIEN
---> NORDRYGGEN GEOLOGI
---> NORGES FJELLHEIMER
-> UTFORSKE NORDRYGGSTIEN
-> LEGG INN GEOFUNN

GER:
-> ÜBER NORDRYGGEN
---> WILLKOMMEN AUF DEM NORDRYGGEN GEOTRAIL
---> NORDRYGGEN GEOLOGIE
---> NORWEGENS BERGREGIONEN
-> ERLEBE DEN NORDRYGGEN GEOTRAIL
-> GEOFUNN BEITRAGEN

**Comment by bokiftw** [comment]
Can you just tell me which page "Explore Nordryggen geotrail" is? Which one from the designs? In order to know which page to link there. If there is no that page yet, you will be able to add it later.

**Comment by diplomod** [comment]
That's the Map

**Comment by bokiftw** [comment]
I added menu for all languages, excluding Map page. You are able to add/change menu whenever you need to, by pressing the pencil icon on the right, next to language definition (NO, DE, EN).
Also, important thing is that, if you want to add some page to the menu, you will have to have it translated  to that actual language. Also, every post has to be translated to language in order to be present on the page. For example, now for Home page in German language, you don't see a slider, because Posts are not translated to german language, but for Norwegian and English they are.

**Comment by diplomod** [comment]
OK - so it's not possible to start with Norwegian only, we always have to translate everything in all 3 languages?

**Comment by bokiftw** [comment]
We can start with Norwegian, in that case it must be default language. The thing is that if someone with language and pick other, Posts which aren't translated won't show up. Or in the beginning to disable other languages so it can't be switched to other.

**Comment by diplomod** [comment]
That's fine. Norwegian shuld be default.
It's just important that we can get started even if we don't have all translations ready.
