### ISSUE TITLE
Optimierung Umsetzung Design von Preview in Map

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#93]
Der Link sollte laut Design weiß sein denk ich:

Online:
![screen shot 2015-03-30 at 09 24 02](https://cloud.githubusercontent.com/assets/7487883/6891819/99688f3e-d6be-11e4-91d1-5dcdd9fb33d6.png)

Design:
![screen shot 2015-03-30 at 09 25 09](https://cloud.githubusercontent.com/assets/7487883/6891843/bf5453fe-d6be-11e4-9dc0-c9a724837ff4.png)

Und der Pfeil am unteren Rand der Preview sollte oberhalb des Icons enden und nicht darin - sieht blöd aus:

Online:
![screen shot 2015-03-30 at 09 25 58](https://cloud.githubusercontent.com/assets/7487883/6891884/f5aff5b6-d6be-11e4-898d-c2f46d8a02a8.png)

Design:
![screen shot 2015-03-30 at 09 26 03](https://cloud.githubusercontent.com/assets/7487883/6891885/f933d194-d6be-11e4-9914-2a07a8bbc48d.png)

**Comment by diplomod** [comment]
fast - ich glaube, die Font ist noch bold - kann das sein? Wirkt noch etwas spärlich.

**Comment by Immoz** [comment]
habs angepasst

**Comment by diplomod** [comment]
sweet
