### ISSUE TITLE
Translation links on home in German

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#95]
I made a mistake with the translation of "See all" to German - quite embarrasing. :)

Below Community and News, it should not say "Siehe alle" but
"Zur Community"
and "Alle News"

**Comment by diplomod** [comment]
Now thats completely wrong: 
![screen shot 2015-04-01 at 22 17 16](https://cloud.githubusercontent.com/assets/7487883/6951627/e45eaf6e-d8bc-11e4-83f1-6758297e2f33.png)
Can I change this somewhere?

**Comment by bokiftw** [comment]
@Immoz Please, update new language files in root folder. So copy ONLY .mo files (en_US.mo, de_DE.mo, nb_NO.mo) into theme root folder (nordryggen) were all files are.

**Comment by diplomod** [comment]
OK, this works now. Thanks
