### ISSUE TITLE
Map: Standardfokus beim Öffnen

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#97]
Die Karte sollte standardmäßig ca. da stehen:
![screen shot 2015-03-30 at 10 31 13](https://cloud.githubusercontent.com/assets/7487883/6892854/eb8fe8ee-d6c7-11e4-9b7f-f0abeccd63a1.png)
Also ein Gebiet anzeigen, welches JOTUNHEIMEN und RONDANE anzeigt.
(kann sich nochmal ändern ;))

Außerdem wäre es super, wenn wir dann einen Button oben rechts platzieren könnten (immer sichtbar):
"Vis Nordryggstien fra sor til nord"
Wenn man darauf klickt, zoomt die Karte genau soweit heraus, dass man den ganzen Trail sieht (mit ein bisschen Platz oben und unten)

**Comment by diplomod** [comment]
Comment: Auf iPhone ist immer oslo anvisiert default, das ist auch unpraktisch. Lieber auch den oben definierten bereich.
Außerdem sind keine Werte default ausgewählt (Geofunn, Nordryggstien)

**Comment by Immoz** [comment]
Momentan zoomt ja die karte auf den Trail, wenn man diesen bei den Filtern auswählt. Soll der Button ("Vis Nordryggstien fra sor til nord") trotzdem noch rein?

**Comment by diplomod** [comment]
Ja - der Trail soll nicht komplett sichbar sein, sondern nur der Part, den ich oben ausgewählt habe (ungefähr). Das Problem ist ja, das Norwegen x-mal höher as breit ist.

Bzgl. Trail: SIehe #102

**Comment by Immoz** [comment]
Ok hab den button eingebaut. Das er beim klick in die map etwas nach oben verschwindet hat mit dem slider-button zu tun. Darum kümmert sich momentan jemand aus dem anderen team.

**Comment by diplomod** [comment]
OK - wird aktuell auch noch von dem Aktivierungs-Bereich oben überlagert. Das meinst du, oder?

Anyway, beim clicken des Button passiert leider nichts...?

**Comment by Immoz** [comment]
Sollte jetzt so aussehen. Zur not evtl nochmal cache checken. Beim klick sollte automatisch über/unter die map gescrollt werden.
![2015-04-01 22_03_32-nordryggstien no _ explore the nordryggstien](https://cloud.githubusercontent.com/assets/1924026/6951374/250ed770-d8bb-11e4-9000-4ff7a275b80b.png)

**Comment by diplomod** [comment]
passt denk ich
