### ISSUE TITLE
Geologi (and fjellheimer and attractions): Can we add an intro text on top of pictures?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#98]
Here:
![screen shot 2015-03-30 at 10 49 19](https://cloud.githubusercontent.com/assets/7487883/6893116/8a43344e-d6ca-11e4-8376-5887ba87b644.png)

**Comment by bokiftw** [comment]
Yes, we can add text there. Will it be dynamic, populated via Wordpress? So in that case I will add new post fields so you will be able to type there.

**Comment by diplomod** [comment]
Yes, exactly.

**Comment by diplomod** [comment]
xx

**Comment by diplomod** [comment]
great. See also #124
