### ISSUE TITLE
Submission page seems cut off

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#99]
There is some issue with the space on this page - left and right, checkboxes are cut off:

![screen shot 2015-03-30 at 09 46 33](https://cloud.githubusercontent.com/assets/7487883/6893343/66936e9a-d6cc-11e4-90a5-50e2aa8c1931.png)
![screen shot 2015-03-30 at 09 46 40](https://cloud.githubusercontent.com/assets/7487883/6893339/668bbf92-d6cc-11e4-808a-493aba046992.png)
![screen shot 2015-03-30 at 09 47 04](https://cloud.githubusercontent.com/assets/7487883/6893341/668d5a50-d6cc-11e4-9cf7-f6e9fd27eb28.png)
![screen shot 2015-03-30 at 09 47 18](https://cloud.githubusercontent.com/assets/7487883/6893340/668c36de-d6cc-11e4-939e-db9a1bbaaf48.png)
![screen shot 2015-03-30 at 09 47 22](https://cloud.githubusercontent.com/assets/7487883/6893342/668d6d1a-d6cc-11e4-8516-7640d96d9d96.png)
![screen shot 2015-03-30 at 09 47 27](https://cloud.githubusercontent.com/assets/7487883/6893346/66a9aac0-d6cc-11e4-94c7-8eeebc0b79f0.png)
![screen shot 2015-03-30 at 09 51 02](https://cloud.githubusercontent.com/assets/7487883/6893345/66a71292-d6cc-11e4-9f4a-7d5933325486.png)

@Immoz Or is it your Baustelle?

**Comment by bokiftw** [comment]
I am not sure how this happened since here it seems fine: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/submit/

Please sign also guys from dokluh

**Comment by Immoz** [comment]
@diplomod Can you try to clear browser-cache? On my browsers (Chrome, FF, Safari) it looks normal:

![2015-03-30 12_49_25-submit _ nordryggstien no](https://cloud.githubusercontent.com/assets/1924026/6895018/b8bb2cf8-d6db-11e4-8ee8-0433c993dfb6.png)

**Comment by diplomod** [comment]
okm- thanks 
@Immoz schau bitte mal

**Comment by diplomod** [comment]
ok - loks good, thanks
